project_id = "protstock_app"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://protstockapp.vercel.app"]
enable_signup = false

[studio]
enabled = true
port = 54323
