import { useEffect, useMemo, useState } from 'react'
import { ChevronDown, Search, SlidersHorizontal, Star } from 'lucide-react'
import { useStockAnalysis, useSymbols, type PriceZone } from '../hooks/useStockAnalysis'
import { openCommandPalette } from './CommandPalette'
import { StockChart } from './StockChart'
import { ZoneEvidence } from './ZoneEvidence'
import { formatMarketPrice } from '../lib/marketUnits'

const patternNames:Record<string,string>={ACCUMULATION_BASE:'Nền tích lũy',DOUBLE_BOTTOM:'Hai đáy',DOUBLE_TOP:'Hai đỉnh',ASCENDING_TRIANGLE:'Tam giác tăng',DESCENDING_TRIANGLE:'Tam giác giảm',SYMMETRICAL_TRIANGLE:'Tam giác cân',BULL_FLAG:'Cờ tăng',BEAR_FLAG:'Cờ giảm'}
const number=(value:number|null|undefined,digits=2)=>value==null?'—':Number(value).toLocaleString('vi-VN',{maximumFractionDigits:digits})
const rangeSize:Record<string,number>={ '1M':22,'3M':66,'6M':132,'1Y':260,'3Y':780,ALL:9999 }
const exchangeLabel=(exchange:string|null|undefined)=>({HOSE:'HSX',HSX:'HSX',HNX:'HNX',UPCOM:'UPCOM'}[exchange??'']??'Đang đồng bộ sàn')

const zoneContextCopy:Record<string,{title:string;message:string}>={
  UP:{title:'Xu hướng tăng',message:'Hỗ trợ là vùng theo dõi nhịp hồi; kháng cự là mốc cần vượt bằng xác nhận, không phải lệnh bán tự động.'},
  DOWN:{title:'Xu hướng giảm',message:'Kháng cự phía trên là vùng hồi kỹ thuật có thể gặp cung. Không xem đó là tín hiệu mua; hỗ trợ chỉ là mốc quản trị rủi ro đến khi có xác nhận.'},
  SIDEWAYS:{title:'Xu hướng đi ngang',message:'Theo dõi biên hỗ trợ–kháng cự. Một vùng chỉ trở thành breakout khi giá đóng cửa vượt vùng và có xác nhận khối lượng.'},
  UNKNOWN:{title:'Xu hướng chưa rõ',message:'Vùng giá là mốc tham chiếu; cần thêm dữ liệu xu hướng trước khi dùng làm luận điểm giao dịch.'},
}
function zoneDistance(zone:PriceZone, close:number|null|undefined) {
  if (!close || close<=0) return 'Chưa có giá đóng cửa'
  if (close>=zone.lower_price&&close<=zone.upper_price) return 'Giá đang trong vùng'
  const boundary=zone.zone_type==='SUPPORT'?zone.upper_price:zone.lower_price
  const distance=Math.abs(close-boundary)/close*100
  return `${number(distance,1)}% phía ${zone.zone_type==='SUPPORT'?'dưới':'trên'}`
}
function ZoneMap({zones,close,trend,timeframe}:{zones:PriceZone[];close:number|null|undefined;trend:string|undefined;timeframe:string}) {
  const state=zoneContextCopy[trend??'']?trend??'UNKNOWN':'UNKNOWN'; const context=zoneContextCopy[state]
  const ranked=(kind:PriceZone['zone_type'])=>zones.filter(zone=>zone.zone_type===kind).sort((a,b)=>{const distance=(zone:PriceZone)=>!close?Infinity:Math.min(Math.abs(close-zone.lower_price),Math.abs(close-zone.upper_price));return distance(a)-distance(b)||b.strength-a.strength}).slice(0,3)
  const groups:[PriceZone['zone_type'],string,string][]=[['RESISTANCE','Kháng cự gần giá','Vùng cản phía trên'],['SUPPORT','Hỗ trợ gần giá','Vùng đệm phía dưới']]
  return <article className={`panel zone-panel zone-context-${state.toLowerCase()}`}><div className="panel-title"><div><h3>Hỗ trợ · kháng cự</h3><small>Bản đồ vùng giá · khung {timeframe} · VND/cổ phiếu</small></div><span>{zones.length} vùng</span></div><div className="zone-context-copy"><b>{context.title}</b><p>{context.message}</p></div><div className="zone-groups">{groups.map(([kind,title,subtitle])=>{const items=ranked(kind);return <section className={`zone-group ${kind.toLowerCase()}`} key={kind}><div className="zone-group-heading"><div><strong>{title}</strong><small>{subtitle}</small></div><span>{items.length}/3</span></div>{items.length?<div className="zone-list">{items.map(zone=><div className={`zone-card ${zone.zone_type==='SUPPORT'?'support':'resistance'}`} key={zone.id}><div className="zone-card-main"><span className="zone-kind">{zone.zone_type==='SUPPORT'?'Hỗ trợ':'Kháng cự'} · {zoneDistance(zone,close)}</span><strong>{formatMarketPrice(zone.lower_price)} <i>—</i> {formatMarketPrice(zone.upper_price)}</strong></div><div className="zone-meta"><span className="zone-touches"><b>{zone.touches}</b><small>lần chạm</small></span><span>Độ mạnh {number(zone.strength,0)}</span></div><ZoneEvidence zone={zone}/></div>)}</div>:<p className="zone-empty">{kind==='SUPPORT'?'Chưa có hỗ trợ đủ pivot để xác nhận.':'Chưa có kháng cự đủ pivot để xác nhận.'}</p>}</section>})}</div></article>
}

export function AnalysisPage({authenticated}:{authenticated:boolean}) {
  const symbols=useSymbols(authenticated); const [selected,setSelected]=useState<string|null>(()=>localStorage.getItem('protstock-symbol')); const [favorites,setFavorites]=useState<string[]>(()=>{ try { return JSON.parse(localStorage.getItem('protstock-favorites') ?? '[]') } catch { return [] } }); const [timeframe,setTimeframe]=useState<'D'|'W'|'M'>('D'); const [range,setRange]=useState('1Y'); const [multiPane,setMultiPane]=useState(()=>localStorage.getItem('protstock-chart-mode')==='triple'); const [indicators,setIndicators]=useState({ma20:true,ma50:true,ma200:false,bollinger:false,rsi:true,macd:false})
  useEffect(()=>{ if(!selected&&symbols.data?.length)setSelected(symbols.data.find(x=>x.symbol==='FPT')?.symbol??symbols.data[0].symbol) },[selected,symbols.data])
  useEffect(()=>{ const listener=(e:Event)=>setSelected((e as CustomEvent).detail); const favoriteListener=(e:Event)=>setFavorites((e as CustomEvent).detail); addEventListener('protstock:symbol',listener); addEventListener('protstock:favorites',favoriteListener); return()=>{removeEventListener('protstock:symbol',listener);removeEventListener('protstock:favorites',favoriteListener)} },[])
  const dailyAnalysis=useStockAnalysis(selected,'D',authenticated); const weeklyAnalysis=useStockAnalysis(selected,'W',authenticated); const monthlyAnalysis=useStockAnalysis(selected,'M',authenticated); const analysis={D:dailyAnalysis,W:weeklyAnalysis,M:monthlyAnalysis}[timeframe]; const snapshot=analysis.data?.technical[0]; const bars=useMemo(()=>analysis.data?.prices.slice(-rangeSize[range])??[],[analysis.data?.prices,range])
  const changePct = bars.length>=2 ? (bars[bars.length-1].close-bars[bars.length-2].close)/bars[bars.length-2].close*100 : null
  const toggle=(key:keyof typeof indicators)=>setIndicators(value=>({...value,[key]:!value[key]})); const toggleFavorite=()=>{if(!selected)return; const next=favorites.includes(selected)?favorites.filter(item=>item!==selected):[selected,...favorites];setFavorites(next);localStorage.setItem('protstock-favorites',JSON.stringify(next));dispatchEvent(new CustomEvent('protstock:favorites',{detail:next}))}
  const chipValue: Record<string, number | null | undefined> = { ma20: snapshot?.sma20, ma50: snapshot?.sma50, ma200: snapshot?.sma200, rsi: snapshot?.rsi14, macd: snapshot?.macd }
  return <section className="workspace-page"><div className="page-title-row"><div><h1>Phân tích mã</h1></div><div className="symbol-picker"><span>Mã cổ phiếu</span><div className="symbol-picker-actions"><button type="button" className={favorites.includes(selected??'')?'star quick-star active':'star quick-star'} aria-label="Thêm mã vào watchlist" onClick={toggleFavorite}><Star size={18} fill={favorites.includes(selected??'')?'currentColor':'none'}/></button><button type="button" onClick={()=>openCommandPalette('symbols')}><span><Search size={16}/> {selected??'Chọn mã'}</span><ChevronDown size={16}/></button></div></div></div>
    <div className="chart-toolbar"><div className="chart-tools" aria-label="Khoảng thời gian">{['1M','3M','6M','1Y','3Y','ALL'].map(item=><button className={range===item?'active':''} onClick={()=>setRange(item)} key={item}>{item==='ALL'?'Tất cả':item}</button>)}</div><div className="chart-tools" aria-label="Khung nến">{([['D','Ngày'],['W','Tuần'],['M','Tháng']] as const).map(([v,l])=><button className={timeframe===v&&!multiPane?'active':''} onClick={()=>{setTimeframe(v);setMultiPane(false);localStorage.setItem('protstock-chart-mode','single')}} key={v}>{l}</button>)}<button className={multiPane?'active':''} onClick={()=>setMultiPane(value=>{const next=!value;localStorage.setItem('protstock-chart-mode',next?'triple':'single');return next})}>M/W/D</button></div></div>
    {analysis.isLoading&&<div className="skeleton-page"><div className="skeleton skeleton-card"/><div className="skeleton-grid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div></div>}{analysis.isError&&<div className="empty-state warning">Chưa đọc được dữ liệu phân tích. Kiểm tra migration và pipeline EOD.</div>}
    {!authenticated&&!analysis.data&&<div className="empty-state"><Search size={25}/><h3>Workspace phân tích đã sẵn sàng</h3><p>Kết nối Supabase để xem chart, mẫu hình và vùng giá của 202 mã.</p></div>}
    {analysis.data&&<><div className="stock-heading"><div><h2>{analysis.data.symbol.symbol}<span className="sector-label">{analysis.data.symbol.sector}</span></h2><p>{analysis.data.symbol.company_name||'Chưa đồng bộ tên doanh nghiệp'} · {exchangeLabel(analysis.data.symbol.exchange)}</p></div><div className={`trend-badge ${snapshot?.trend_state?.toLowerCase()??''}`}>{snapshot?.trend_state??'CHƯA CÓ SNAPSHOT'}</div></div>
      <div className="chart-toolbar indicator-toolbar"><div className="chart-tools">{([['ma20','MA20'],['ma50','MA50'],['ma200','MA200'],['bollinger','Bollinger'],['rsi','RSI'],['macd','MACD']] as const).map(([key,label])=>{const value=chipValue[key];const display=key==='rsi'?number(value):formatMarketPrice(value);return <button key={key} className={indicators[key]?'active':''} onClick={()=>toggle(key)}>{label}{indicators[key]&&value!=null?<b>{display}</b>:null}</button>})}</div><button className="icon-button"><SlidersHorizontal size={16}/></button></div>
      {multiPane?<div className="multi-chart-studio">{([['M','Tháng'],['W','Tuần'],['D','Ngày']] as const).map(([pane,paneLabel])=>{const paneAnalysis={D:dailyAnalysis,W:weeklyAnalysis,M:monthlyAnalysis}[pane];const paneBars=paneAnalysis.data?.prices.slice(-(pane==='M'?60:pane==='W'?156:260))??[];return <article className="multi-chart-pane" key={pane}><div className="multi-chart-pane-title"><span>{pane}</span><strong>Khung {paneLabel}</strong><small>{paneBars.length} nến · đồng bộ con trỏ</small></div>{paneBars.length?<StockChart bars={paneBars} zones={paneAnalysis.data?.zones} patterns={paneAnalysis.data?.patterns} indicators={indicators} paneId={pane} paneLabel={`Khung ${paneLabel}`}/>:<div className="empty-state compact">Chưa có dữ liệu {paneLabel.toLowerCase()}.</div>}</article>})}</div>:bars.length?<StockChart bars={bars} zones={analysis.data.zones} patterns={analysis.data.patterns} indicators={indicators} paneId={timeframe} paneLabel={`Khung ${timeframe}`}/>:<div className="empty-state">Chưa có OHLCV. Pipeline EOD sẽ điền dữ liệu sau phiên.</div>}
      <div className="metric-grid">{[['Đóng cửa',snapshot?.close,false,true],['Thay đổi phiên',changePct,true,false],['ATR 14',snapshot?.atr14,false,true],['Volume / TB20',snapshot?.volume_ratio20,false,false]].map(([label,value,isPct,isPrice])=><article className="metric-card" key={label as string}><span>{label}</span><strong className={isPct&&typeof value==='number'?(value<0?'negative':'positive'):undefined}>{isPct&&typeof value==='number'?`${value>=0?'+':''}${value.toFixed(2)}%`:isPrice?formatMarketPrice(value as number|null):number(value as number|null)}</strong></article>)}</div>
      <div className="analysis-columns"><article className="panel"><div className="panel-title"><h3>Mẫu hình trên chart</h3><span>{analysis.data.patterns.length}</span></div>{analysis.data.patterns.length?analysis.data.patterns.map(pattern=><div className="pattern-row" key={pattern.id}><div><strong>{patternNames[pattern.pattern_type]??pattern.pattern_type}</strong><small>{pattern.timeframe} · {pattern.state} · {pattern.direction}</small></div><div className="score">{number(pattern.quality_score,0)}</div><p>{pattern.reasons.join(' · ')}</p></div>):<p className="muted">Chưa phát hiện mẫu hình đủ tiêu chuẩn.</p>}</article>{analysis.data.zones.length?<ZoneMap zones={analysis.data.zones} close={snapshot?.close} trend={snapshot?.trend_state} timeframe={timeframe}/>:<article className="panel zone-panel"><div className="panel-title"><h3>Hỗ trợ · kháng cự</h3></div><p className="muted">Chưa xác định được vùng giá đủ mạnh.</p></article>}</div>
      <article className="panel"><div className="panel-title"><h3>Luận điểm hệ thống</h3><span>GIẢI THÍCH</span></div><ul className="reason-list"><li>Xu hướng D/W/M được đánh giá độc lập.</li><li>Mẫu hình là bằng chứng bổ sung, không tự phát tín hiệu.</li><li>Breakout cần đóng cửa ngoài vùng cản.</li><li>Dữ liệu chỉ dùng từ ngày <code>available_from</code>.</li></ul></article>
    </>}</section>
}
