import { FormEvent, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../lib/supabase'
import { useSymbols } from '../hooks/useStockAnalysis'

export function BacktestPage({ authenticated }: { authenticated: boolean }) {
  const client = useQueryClient(); const symbols = useSymbols(authenticated)
  const [symbol, setSymbol] = useState('FPT'); const [versionId, setVersionId] = useState('')
  const [dateFrom, setDateFrom] = useState('2024-01-01'); const [dateTo, setDateTo] = useState(new Date().toISOString().slice(0, 10))
  const versions = useQuery({ queryKey: ['rule-versions'], enabled: authenticated && Boolean(supabase), queryFn: async () => { const { data, error } = await supabase!.from('rule_versions').select('id,version,rules!inner(name,status)').eq('rules.status', 'ACTIVE').order('created_at', { ascending: false }); if (error) throw error; return data ?? [] } })
  const runs = useQuery({ queryKey: ['backtests'], enabled: authenticated && Boolean(supabase), queryFn: async () => { const { data, error } = await supabase!.from('backtest_runs').select('id,name,date_from,date_to,status,metrics,benchmark_metrics,created_at,symbols(symbol),rule_versions(rules(name))').order('created_at', { ascending: false }); if (error) throw error; return data ?? [] } })
  async function queue(event: FormEvent) { event.preventDefault(); const chosen = versionId || versions.data?.[0]?.id; const symbolId = symbols.data?.find(item => item.symbol === symbol)?.id; if (!chosen || !symbolId) return; await supabase!.from('backtest_runs').insert({ rule_version_id: chosen, symbol_id: symbolId, timeframe: 'D', name: `${symbol} · ${dateFrom} → ${dateTo}`, date_from: dateFrom, date_to: dateTo, assumptions: { initial_capital: 100000000, fee_rate: .0015, sell_tax_rate: .001, slippage_rate: .001, stop_loss_pct: .07, trailing_stop_pct: .1, time_stop_bars: 20 } }); client.invalidateQueries({ queryKey: ['backtests'] }) }
  return <section className="workspace-page"><span className="eyebrow">PHASE 4 · WALK-FORWARD</span><h1>Backtest</h1>
    <div className="analysis-columns"><form className="panel rule-form" onSubmit={queue}><label>Rule version<select value={versionId} onChange={e => setVersionId(e.target.value)}><option value="">Chọn rule đang bật</option>{(versions.data ?? []).map((item: any) => <option value={item.id} key={item.id}>{item.rules?.name} · v{item.version}</option>)}</select></label><label>Mã<select value={symbol} onChange={e => setSymbol(e.target.value)}>{(symbols.data ?? []).map(item => <option key={item.id}>{item.symbol}</option>)}</select></label><label>Từ ngày<input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)}/></label><label>Đến ngày<input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)}/></label><button disabled={!versions.data?.length}>Xếp hàng backtest</button></form>
    <article className="panel"><div className="panel-title"><h3>Giả định mặc định</h3><span>POINT-IN-TIME</span></div><ul className="reason-list"><li>Vào lệnh ở giá mở cửa phiên kế tiếp.</li><li>Phí 0,15%, thuế bán 0,1%, trượt giá 0,1%.</li><li>Stop 7%, trailing 10%, time-stop 20 bars.</li><li>Rule version được khóa cùng kết quả.</li></ul></article></div>
    <article className="panel"><div className="panel-title"><h3>Kết quả</h3><span>{runs.data?.length ?? 0}</span></div>{runs.isError && <p className="form-error">Chưa đọc được schema Phase 4.</p>}{(runs.data ?? []).map((run: any) => <div className="rule-row" key={run.id}><div><strong>{run.name}</strong><small>{run.status === 'SUCCEEDED' ? `Return ${((run.metrics?.total_return ?? 0) * 100).toFixed(1)}% · Max DD ${((run.metrics?.max_drawdown ?? 0) * 100).toFixed(1)}% · Sharpe ${(run.metrics?.sharpe ?? 0).toFixed(2)}` : 'GitHub Actions sẽ xử lý sau phiên gần nhất.'}</small></div><span>{run.status}</span></div>)}{!runs.isLoading && !runs.data?.length && <p className="muted">Chưa có lượt backtest.</p>}</article>
  </section>
}
