import { useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, BookOpen, BriefcaseBusiness, Clock3, FlaskConical, LayoutDashboard, Search, Settings, ShieldCheck, Star, Workflow, X } from 'lucide-react'

export interface SymbolOption { symbol: string; sector?: string | null; exchange?: string | null }
const destinations = [
  { id: 'today', label: 'Tổng quan', hint: 'Bức tranh hôm nay', icon: LayoutDashboard }, { id: 'analysis', label: 'Phân tích mã', hint: 'Chart và tín hiệu đa khung', icon: BarChart3 }, { id: 'screener', label: 'Screener', hint: 'Lọc cơ hội sau phiên', icon: Search }, { id: 'rules', label: 'Rule Studio', hint: 'Xây dựng kỷ luật giao dịch', icon: Workflow }, { id: 'backtest', label: 'Backtest', hint: 'Kiểm chứng rule', icon: FlaskConical }, { id: 'portfolio', label: 'Danh mục', hint: 'Vị thế và mức rủi ro', icon: BriefcaseBusiness }, { id: 'journal', label: 'Nhật ký', hint: 'Vòng phản hồi quyết định', icon: BookOpen }, { id: 'settings', label: 'Cài đặt', hint: 'Hệ thống và tài khoản', icon: Settings },
]
function storedList(key: string) { try { return JSON.parse(localStorage.getItem(key) ?? '[]') as string[] } catch { return [] } }
export function openCommandPalette(mode: 'all' | 'symbols' = 'all') { window.dispatchEvent(new CustomEvent('protstock:command', { detail: { mode } })) }

export function CommandPalette({ symbols = [], onSymbol }: { symbols?: SymbolOption[]; onSymbol?: (symbol: string) => void }) {
  const [open, setOpen] = useState(false); const [mode, setMode] = useState<'all' | 'symbols'>('all'); const [query, setQuery] = useState(''); const [favorites, setFavorites] = useState<string[]>(() => storedList('protstock-favorites')); const [recent, setRecent] = useState<string[]>(() => storedList('protstock-recent')); const inputRef = useRef<HTMLInputElement>(null)
  useEffect(() => { const keyboard = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; const typing = target?.tagName === 'INPUT' || target?.tagName === 'TEXTAREA' || target?.isContentEditable; if (((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') || (event.key === '/' && !typing)) { event.preventDefault(); setMode('all'); setOpen(value => !value) } if (event.key === 'Escape') setOpen(false) }; const custom = (event: Event) => { const detail = (event as CustomEvent).detail; setMode(detail?.mode ?? 'all'); setOpen(true) }; addEventListener('keydown', keyboard); addEventListener('protstock:command', custom); return () => { removeEventListener('keydown', keyboard); removeEventListener('protstock:command', custom) } }, [])
  useEffect(() => { if (open) { setQuery(''); setTimeout(() => inputRef.current?.focus(), 30) } }, [open])
  const filteredSymbols = useMemo(() => { const needle = query.trim().toLowerCase(); return symbols.filter(item => !needle || item.symbol.toLowerCase().includes(needle) || item.sector?.toLowerCase().includes(needle)).sort((a,b) => Number(favorites.includes(b.symbol)) - Number(favorites.includes(a.symbol))).slice(0,18) }, [symbols, favorites, query])
  const filteredDestinations = destinations.filter(item => mode === 'all' && (!query || `${item.label} ${item.hint}`.toLowerCase().includes(query.toLowerCase())))
  function chooseSymbol(symbol: string) { const next=[symbol,...recent.filter(item=>item!==symbol)].slice(0,5); setRecent(next); localStorage.setItem('protstock-recent',JSON.stringify(next)); localStorage.setItem('protstock-symbol',symbol); onSymbol?.(symbol); location.hash='analysis'; dispatchEvent(new CustomEvent('protstock:symbol',{detail:symbol})); setOpen(false) }
  function toggleFavorite(symbol:string) { const next=favorites.includes(symbol)?favorites.filter(item=>item!==symbol):[symbol,...favorites]; setFavorites(next); localStorage.setItem('protstock-favorites',JSON.stringify(next)); dispatchEvent(new CustomEvent('protstock:favorites',{detail:next})) }
  function submitSearch(event: React.FormEvent) { event.preventDefault(); if (filteredSymbols[0]) chooseSymbol(filteredSymbols[0].symbol); else if (filteredDestinations[0]) { location.hash=filteredDestinations[0].id; setOpen(false) } }
  if (!open) return null
  return <div className="command-backdrop" role="presentation" onMouseDown={()=>setOpen(false)}><section className="command-dialog" role="dialog" aria-modal="true" aria-label="Tìm kiếm và điều hướng" onMouseDown={event=>event.stopPropagation()}><form className="command-input" onSubmit={submitSearch}><Search size={19}/><input ref={inputRef} value={query} onChange={event=>setQuery(event.target.value)} placeholder={mode==='symbols'?'Tìm mã hoặc ngành…':'Tìm mã hoặc chuyển nhanh tới…'}/><kbd>↵</kbd><button type="button" aria-label="Đóng" onClick={()=>setOpen(false)}><X size={18}/></button></form><div className="command-results">{!query&&recent.length>0&&<div className="command-section"><div className="command-label"><span><Clock3 size={13}/> Gần đây</span></div><div className="recent-chips">{recent.map(symbol=><button key={symbol} onClick={()=>chooseSymbol(symbol)}>{symbol}</button>)}</div></div>}{filteredSymbols.length>0&&<div className="command-section"><div className="command-label"><span>Mã cổ phiếu</span><small>{favorites.length} đang theo dõi</small></div>{filteredSymbols.map(item=><div className="command-row" key={item.symbol}><button className="command-main" onClick={()=>chooseSymbol(item.symbol)}><span className="symbol-avatar">{item.symbol.slice(0,2)}</span><span><strong>{item.symbol}</strong><small>{item.sector||'Chưa phân ngành'} · {item.exchange||'VN'}</small></span></button><button type="button" className={favorites.includes(item.symbol)?'star active':'star'} aria-label={`${favorites.includes(item.symbol)?'Bỏ ghim':'Thêm watchlist'} ${item.symbol}`} onClick={()=>toggleFavorite(item.symbol)}><Star size={18} fill={favorites.includes(item.symbol)?'currentColor':'none'}/></button></div>)}</div>}{filteredDestinations.length>0&&<div className="command-section"><div className="command-label"><span>Đi tới</span></div>{filteredDestinations.map(item=><button type="button" className="command-main destination" key={item.id} onClick={()=>{location.hash=item.id;setOpen(false)}}><span className="command-icon"><item.icon size={18}/></span><span><strong>{item.label}</strong><small>{item.hint}</small></span></button>)}</div>}{!filteredSymbols.length&&!filteredDestinations.length&&<div className="command-empty"><ShieldCheck size={24}/><strong>Không tìm thấy kết quả</strong><span>Thử mã cổ phiếu hoặc tên chức năng khác.</span></div>}</div><footer className="command-footer"><span><kbd>↵</kbd> chọn kết quả đầu tiên</span><span><kbd>Ctrl K</kbd> mở nhanh</span><span>Dữ liệu EOD</span></footer></section></div>
}
