import { useQuery } from '@tanstack/react-query'
import { engineGuides } from '../lib/engineCatalog'
import { supabase } from '../lib/supabase'

export function EngineGuide() {
  const outcomes=useQuery({queryKey:['engine-outcome-stats'],enabled:Boolean(supabase),queryFn:async()=>{const {data,error}=await supabase!.from('engine_outcome_stats').select('*').order('engine_name').order('horizon_days');if(error)throw error;return data??[]}})
  return <>
    <details className="guide-group"><summary>Nguyên lý Core Engine và Core Pack <small>7 NGUỒN</small></summary><div className="guide-group-content"><p>Các nguồn đề xuất → bộ lọc dữ liệu/rủi ro chung → tổng hợp theo mã, ngày và khung. Bật nhiều nguồn không đồng nghĩa nhiều bằng chứng độc lập. Điểm 70/90/98 là mức đồng thuận, không phải xác suất thắng.</p>{engineGuides.map(item=><section key={item.name}><h3>{item.name}</h3><p>{item.detail}</p></section>)}</div></details>
    <details className="guide-group"><summary>Bộ lọc chung và lý do bị chặn</summary><div className="guide-group-content"><p>Giá cổ phiếu nguồn lưu theo nghìn đồng; thanh khoản được đổi về đồng trước khi so ngưỡng 300 triệu/phiên. Vốn, giá vốn và stop trong danh mục nhập bằng đồng. Ngưỡng ngành mặc định 30% tổng vốn sau khi thêm vị thế, dùng khối lượng tính theo ngân sách rủi ro.</p><p>Dữ liệu cũ, thiếu bối cảnh thị trường, breadth dưới 40%, VN-Index giảm, tháng giảm/chưa rõ, stop không hợp lệ hoặc vượt giới hạn danh mục đều chặn mua mới. EXIT khi vị thế thủng stop không bị bộ lọc mua chặn. REDUCE/EXIT khi không nắm giữ chuyển thành WATCH kèm lý do.</p><p>Chưa khai báo danh mục: tín hiệu là ứng viên, chưa có sizing cá nhân. Không dùng danh mục hiện tại để giả lập vị thế trong quá khứ. Các lượt đánh giá và lý do bị chặn được lưu trong signal_evaluations.</p></div></details>
    <details className="guide-group"><summary>Ngày, Tuần, Tháng và đánh giá kết quả</summary><div className="guide-group-content"><p>Tháng định hướng (EMA10/SMA20), tuần tìm setup, ngày kích hoạt. W/M chỉ xác nhận khi đã quan sát phiên đầu kỳ mới; ngày tín hiệu là ngày xác nhận, không ghi ngược về kỳ trước. Nến đang hình thành vẫn có trên chart nhưng không tạo sự kiện W/M chính thức. Không bắt buộc ba khung cùng BUY.</p><p>Kết quả được đánh giá sau 5/10/20 phiên có dữ liệu, mỗi mốc có thể hoàn thành riêng. Lợi suất là biến động giá từ đóng cửa ngày tín hiệu, chưa gồm phí hay giá khớp thực tế; REDUCE/EXIT cần đọc như diễn biến sau cảnh báo, không coi lợi suất dương là giao dịch thắng. Chưa dùng kết quả để tự thay ngưỡng.</p>{outcomes.isLoading?<p>Đang đọc kết quả…</p>:outcomes.isError?<p className="muted">Chưa đọc được thống kê đánh giá.</p>:!outcomes.data?.length?<p className="muted">Chưa có mẫu đủ thời gian đánh giá. Không suy diễn hiệu quả khi chưa có mẫu.</p>:<div className="outcome-review">{outcomes.data.map((row:any,index:number)=><article key={index}><strong>{row.engine_name??'Core Engine lịch sử'} · {row.timeframe} · {row.action}</strong><span>{row.horizon_days} phiên · {row.sample_size} mẫu</span><small>Biến động giá TB: {(Number(row.average_forward_return)*100).toFixed(2)}% · Drawdown TB: {(Number(row.average_drawdown)*100).toFixed(2)}%</small></article>)}</div>}</div></details>
  </>
}
