import { FormEvent, useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Plus } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useSymbols } from '../hooks/useStockAnalysis'
export function JournalPage({authenticated}:{authenticated:boolean}){const client=useQueryClient();const symbols=useSymbols(authenticated);const[symbol,setSymbol]=useState('');const[decision,setDecision]=useState('SKIP');const[setup,setSetup]=useState('');const[marketState,setMarketState]=useState('');const[rationale,setRationale]=useState('');const[formOpen,setFormOpen]=useState(false);const[toast,setToast]=useState('');const entries=useQuery({queryKey:['journal'],enabled:authenticated&&Boolean(supabase),queryFn:async()=>{const{data,error}=await supabase!.from('journal_entries').select('id,decision_date,decision,setup_type,market_state,rationale,result_pct,outcome,lesson,symbols(symbol,sector)').order('decision_date',{ascending:false}).limit(100);if(error)throw error;return data??[]}});const rows=(entries.data ?? []) as any[];const closed=rows.filter(x=>x.outcome!=='OPEN');const wins=closed.filter(x=>x.outcome==='WIN');const winRate=closed.length?wins.length/closed.length*100:0;const review=useMemo(()=>['setup_type','symbols.sector','market_state'].map(field=>Object.entries(closed.reduce((all:any,x:any)=>{const key=field==='symbols.sector'?x.symbols?.sector:x[field];if(!key)return all;all[key]??={total:0,loss:0};all[key].total++;all[key].loss+=x.outcome==='LOSS'?1:0;return all},{})).sort((a:any,b:any)=>b[1].loss-a[1].loss).slice(0,4)),[rows.length])
 async function save(event:FormEvent){event.preventDefault();const symbolId=symbols.data?.find(x=>x.symbol===symbol)?.id;if(!supabase||!symbolId){setToast('Bản xem trước: quyết định đã được ghi nhận');setFormOpen(false);setTimeout(()=>setToast(''),2500);return}await supabase.from('journal_entries').insert({symbol_id:symbolId,decision_date:new Date().toISOString().slice(0,10),decision,setup_type:setup||null,market_state:marketState||null,rationale,outcome:'OPEN'});setRationale('');client.invalidateQueries({queryKey:['journal']});setToast('Đã lưu quyết định');setFormOpen(false);setTimeout(()=>setToast(''),3000)}
 return <section className="workspace-page"><span className="eyebrow">JOURNAL · FEEDBACK LOOP</span><div className="page-title-row"><div><h1>Nhật ký quyết định</h1><p className="muted">Đo chất lượng quyết định, không chỉ kết quả giao dịch.</p></div><button className="primary-button" onClick={()=>setFormOpen(true)}><Plus size={16}/> Ghi quyết định</button></div><div className="metric-grid"><article className="metric-card"><span>Tổng quyết định</span><strong>{rows.length}</strong></article><article className="metric-card"><span>Tỷ lệ thắng</span><strong>{winRate.toFixed(0)}%</strong></article><article className="metric-card"><span>Expectancy</span><strong>—</strong></article><article className="metric-card"><span>Kỷ luật rule</span><strong>—</strong></article></div>
 <div className="analytics-grid journal-analytics"><article className="analytic-card"><h3>Hiệu suất đã đóng</h3><strong>{closed.length ? `${closed.length} quyết định` : '—'}</strong><p className="muted">Chỉ tổng hợp từ nhật ký đã có kết quả.</p></article><article className="analytic-card"><h3>Win / Loss</h3><strong>{closed.length ? `${wins.length} / ${closed.length - wins.length}` : '—'}</strong><p className="muted">Tỷ lệ thắng: {closed.length ? `${winRate.toFixed(0)}%` : 'chưa có dữ liệu'}.</p></article><article className="analytic-card"><h3>Phân tích thua lỗ</h3><p className="muted">Mẫu lỗi sẽ xuất hiện sau khi có các lệnh đã đóng để đối chiếu.</p></article></div>
 <article className="panel"><div className="panel-title"><h3>Dòng thời gian quyết định</h3><span>{rows.length} BẢN GHI</span></div>{rows.map(item=><div className="journal-timeline" key={item.id}><span className={`timeline-dot ${item.outcome?.toLowerCase()}`}/><div><strong>{item.symbols?.symbol} · {item.decision}</strong><small>{item.decision_date} · {item.setup_type??'Chưa setup'} · {item.market_state??'Chưa phân loại'}</small><p>{item.rationale}</p>{item.lesson&&<em>Bài học: {item.lesson}</em>}</div><b className={Number(item.result_pct)<0?'negative':'positive'}>{Number(item.result_pct??0)>0?'+':''}{Number(item.result_pct??0).toFixed(2)}%</b></div>)}</article>
 <article className="panel"><div className="panel-title"><h3>Review theo nhóm</h3><span>CHỈ LỆNH ĐÃ ĐÓNG</span></div><div className="review-grid">{['Theo setup','Theo ngành','Theo thị trường'].map((title,index)=><div key={title}><strong>{title}</strong>{review[index].map(([name,value]:any)=><div className="rule-row" key={name}><div><strong>{name}</strong><small>{value.total} quyết định</small></div><span>{value.loss} LOSS</span></div>)}</div>)}</div></article>
 {formOpen&&<div className="sheet-backdrop" onMouseDown={()=>setFormOpen(false)}><form className="bottom-sheet position-sheet rule-form" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="sheet-title"><div><span className="eyebrow">NEW JOURNAL ENTRY</span><h2>Ghi quyết định</h2></div></div><label>Mã<select value={symbol} onChange={e=>setSymbol(e.target.value)}>{<><option value="">Chọn mã</option>{(symbols.data??[]).map(item=><option key={item.id}>{item.symbol}</option>)}</>}</select></label><label>Quyết định<select value={decision} onChange={e=>setDecision(e.target.value)}>{['BUY','SKIP','SELL','HOLD','STOP'].map(x=><option key={x}>{x}</option>)}</select></label><label>Setup<input value={setup} onChange={e=>setSetup(e.target.value)} placeholder="DOUBLE_BOTTOM"/></label><label>Trạng thái thị trường<input value={marketState} onChange={e=>setMarketState(e.target.value)} placeholder="VNINDEX_UP"/></label><label>Lý do<textarea rows={4} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><button>Lưu quyết định</button></form></div>}{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</section> }


