import { FormEvent, useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../lib/supabase'
import { useSymbols } from '../hooks/useStockAnalysis'

export function JournalPage({ authenticated }: { authenticated: boolean }) {
  const client = useQueryClient(); const symbols = useSymbols(authenticated)
  const [symbol, setSymbol] = useState('FPT'); const [decision, setDecision] = useState('SKIP'); const [setup, setSetup] = useState(''); const [marketState, setMarketState] = useState(''); const [rationale, setRationale] = useState('')
  const entries = useQuery({ queryKey: ['journal'], enabled: authenticated && Boolean(supabase), queryFn: async () => { const { data, error } = await supabase!.from('journal_entries').select('id,decision_date,decision,setup_type,market_state,rationale,result_pct,outcome,lesson,symbols(symbol,sector)').order('decision_date', { ascending: false }).limit(100); if (error) throw error; return data ?? [] } })
  async function save(event: FormEvent) { event.preventDefault(); const symbolId = symbols.data?.find(item => item.symbol === symbol)?.id; if (!symbolId || !rationale.trim()) return; await supabase!.from('journal_entries').insert({ symbol_id: symbolId, decision_date: new Date().toISOString().slice(0, 10), decision, setup_type: setup || null, market_state: marketState || null, rationale, outcome: 'OPEN' }); setRationale(''); client.invalidateQueries({ queryKey: ['journal'] }) }
  async function closeEntry(id: string, outcome: string, result_pct: number, lesson: string) { await supabase!.from('journal_entries').update({ outcome, result_pct, lesson }).eq('id', id); client.invalidateQueries({ queryKey: ['journal'] }) }
  const review = useMemo(() => ['setup_type', 'symbols.sector', 'market_state'].map(field => Object.entries((entries.data ?? []).filter((x: any) => x.outcome !== 'OPEN').reduce((all: any, x: any) => { const key = field === 'symbols.sector' ? x.symbols?.sector : x[field]; if (!key) return all; all[key] ??= { total: 0, loss: 0 }; all[key].total++; all[key].loss += x.outcome === 'LOSS' ? 1 : 0; return all }, {})).sort((a: any, b: any) => b[1].loss - a[1].loss).slice(0, 5)), [entries.data])
  const losses = (entries.data ?? []).filter((item: any) => item.outcome === 'LOSS')
  return <section className="workspace-page"><span className="eyebrow">PHASE 5 · FEEDBACK LOOP</span><h1>Nhật ký quyết định</h1>
    <div className="metric-grid"><article className="metric-card"><span>Tổng quyết định</span><strong>{entries.data?.length ?? 0}</strong></article><article className="metric-card"><span>Lệnh sai</span><strong>{losses.length}</strong></article><article className="metric-card"><span>Setup sai nhiều nhất</span><strong>{losses[0]?.setup_type ?? '—'}</strong></article><article className="metric-card"><span>Ngành cần lưu ý</span><strong>{(losses[0] as any)?.symbols?.sector ?? '—'}</strong></article></div>
    <div className="analysis-columns"><form className="panel rule-form" onSubmit={save}><label>Mã<select value={symbol} onChange={e => setSymbol(e.target.value)}>{(symbols.data ?? []).map(item => <option key={item.id}>{item.symbol}</option>)}</select></label><label>Quyết định<select value={decision} onChange={e => setDecision(e.target.value)}>{['BUY','SKIP','SELL','HOLD','STOP'].map(item => <option key={item}>{item}</option>)}</select></label><label>Setup / mẫu hình<input value={setup} onChange={e => setSetup(e.target.value)} placeholder="DOUBLE_BOTTOM" /></label><label>Trạng thái thị trường<input value={marketState} onChange={e => setMarketState(e.target.value)} placeholder="VNINDEX_UP" /></label><label>Lý do<textarea rows={4} value={rationale} onChange={e => setRationale(e.target.value)} /></label><button>Lưu quyết định</button></form>
    <article className="panel"><div className="panel-title"><h3>Dòng thời gian</h3><span>{entries.data?.length ?? 0}</span></div>{(entries.data ?? []).map((item: any) => <div className="journal-item" key={item.id}><div className="rule-row"><div><strong>{item.symbols?.symbol} · {item.decision}</strong><small>{item.decision_date} · {item.setup_type ?? 'Chưa setup'} · {item.market_state ?? 'Chưa phân loại'} · {item.rationale}</small></div><span>{item.outcome ?? 'OPEN'}</span></div>{item.outcome === 'OPEN' && <ReviewForm onSave={(outcome, result, lesson) => closeEntry(item.id, outcome, result, lesson)} />}{item.outcome !== 'OPEN' && <small className="muted">Kết quả {Number(item.result_pct ?? 0).toFixed(2)}% · {item.lesson || 'Chưa ghi bài học'}</small>}</div>)}</article></div>
    <article className="panel"><div className="panel-title"><h3>Review hàng tháng</h3><span>Chỉ lệnh đã đóng</span></div><div className="review-grid">{['Theo setup','Theo ngành','Theo thị trường'].map((title, index) => <div key={title}><strong>{title}</strong>{review[index].length ? review[index].map(([name, value]: any) => <div className="rule-row" key={name}><div><strong>{name}</strong><small>{value.total} quyết định</small></div><span>{value.loss} LOSS</span></div>) : <p className="muted">Chưa đủ dữ liệu review.</p>}</div>)}</div></article>
  </section>
}

function ReviewForm({ onSave }: { onSave: (outcome: string, result: number, lesson: string) => void }) { const [outcome, setOutcome] = useState('WIN'); const [result, setResult] = useState(0); const [lesson, setLesson] = useState(''); return <div className="journal-close"><select value={outcome} onChange={e => setOutcome(e.target.value)}>{['WIN','LOSS','BREAKEVEN','CANCELLED'].map(x => <option key={x}>{x}</option>)}</select><input type="number" step="0.01" value={result} onChange={e => setResult(Number(e.target.value))} /><input value={lesson} onChange={e => setLesson(e.target.value)} placeholder="Bài học" /><button type="button" onClick={() => onSave(outcome, result, lesson)}>Chốt review</button></div> }
