import { FormEvent, useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, Plus, WalletCards } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { SoftSelect } from './SoftSelect'
import { SymbolAutocomplete } from './SymbolAutocomplete'
import { CurrencyInput } from './CurrencyInput'
import { useSymbols } from '../hooks/useStockAnalysis'
import { formatVnd } from '../lib/marketUnits'

const transactionLabels = { BUY_NEW: 'Mua mới', BUY_ADD: 'Mua thêm', SELL_REDUCE: 'Bán giảm', SELL_CLOSE: 'Đóng vị thế', STOP_UPDATE: 'Điều chỉnh stop' } as const
type TransactionAction = keyof typeof transactionLabels
const money = (value: number) => formatVnd(value)

export function PortfolioPage({ authenticated }: { authenticated: boolean }) {
  const client = useQueryClient(); const symbols = useSymbols(authenticated)
  const [setupOpen, setSetupOpen] = useState(false); const [tradeOpen, setTradeOpen] = useState(false); const [toast, setToast] = useState('')
  const [initialCapital, setInitialCapital] = useState(100_000_000); const [maxRisk, setMaxRisk] = useState(1)
  const [symbol, setSymbol] = useState(''); const [action, setAction] = useState<TransactionAction>('BUY_NEW'); const [quantity, setQuantity] = useState(100); const [price, setPrice] = useState(0); const [stop, setStop] = useState(0); const [note, setNote] = useState(''); const [hoveredSector, setHoveredSector] = useState<string | null>(null)
  const portfolio = useQuery({ queryKey: ['portfolio'], enabled: authenticated && Boolean(supabase), queryFn: async () => { const { data, error } = await supabase!.from('portfolios').select('id,name,capital,max_risk_per_trade_pct,positions(id,symbol_id,quantity,average_cost,stop_price,opened_at,thesis,symbols(symbol,sector))').limit(1).maybeSingle(); if (error) throw error; return data } })
  const positions = (portfolio.data?.positions ?? []) as any[]; const managed = Number(portfolio.data?.capital ?? 0)
  const deployed = positions.reduce((sum, item) => sum + Number(item.average_cost) * Number(item.quantity), 0); const deployedPct = managed ? deployed / managed * 100 : 0
  const sizing = useMemo(() => { const unitRisk = price - stop; return unitRisk > 0 && managed > 0 ? Math.floor(managed * Number(portfolio.data?.max_risk_per_trade_pct ?? 0) / 100 / unitRisk) : 0 }, [price, stop, managed, portfolio.data?.max_risk_per_trade_pct])
  const totalRisk = managed > 0 ? positions.reduce((sum, item) => sum + Math.max(0, (Number(item.average_cost) - Number(item.stop_price)) * Number(item.quantity)), 0) / managed * 100 : 0
  const allocation = useMemo(() => { const grouped = positions.reduce((all: Record<string, number>, item) => { const sector = item.symbols?.sector || 'Khác'; all[sector] = (all[sector] || 0) + Number(item.average_cost) * Number(item.quantity); return all }, {}); const total = Object.values(grouped).reduce((sum, value) => sum + value, 0); const colors = ['#d7ff52', '#55e6b1', '#5d85ff', '#efbf62', '#c88cff']; let cursor = 0; return Object.entries(grouped).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([label, value], index) => { const start = cursor; const pct = total ? value / total * 100 : 0; cursor += pct; return { label, value, pct, capitalPct: managed ? value / managed * 100 : 0, color: colors[index], start, end: cursor } }) }, [positions, managed])
  const donut = allocation.length ? `conic-gradient(${allocation.map(item => `${item.color} ${item.start}% ${item.end}%`).join(',')})` : '#1b2c24'; const concentration = allocation.find(item => item.capitalPct > 40); const hovered = allocation.find(item => item.label === hoveredSector)
  const notify = (message: string) => { setToast(message); setTimeout(() => setToast(''), 3200) }
  const openTrade = (nextAction: TransactionAction = 'BUY_NEW', ticker = '') => { setAction(nextAction); setSymbol(ticker); setQuantity(100); setPrice(0); setStop(0); setNote(''); setTradeOpen(true) }
  const openCapitalSetup = () => { setInitialCapital(managed || 100_000_000); setMaxRisk(Number(portfolio.data?.max_risk_per_trade_pct ?? 1)); setSetupOpen(true) }
  async function createPortfolio(event: FormEvent) { event.preventDefault(); if (!supabase || initialCapital <= 0 || maxRisk <= 0) return; const query = portfolio.data ? supabase.from('portfolios').update({ capital: initialCapital, max_risk_per_trade_pct: maxRisk }).eq('id', portfolio.data.id) : supabase.from('portfolios').insert({ name: 'Danh mục Prot', capital: initialCapital, max_risk_per_trade_pct: maxRisk }); const { error } = await query; if (error) return notify(`Không thể lưu vốn: ${error.message}`); client.invalidateQueries({ queryKey: ['portfolio'] }); setSetupOpen(false); notify(portfolio.data ? 'Đã cập nhật vốn quản lý' : 'Đã khởi tạo vốn quản lý') }
  async function submitTransaction(event: FormEvent) { event.preventDefault(); const symbolId = symbols.data?.find(item => item.symbol === symbol)?.id; if (!supabase || !portfolio.data || !symbolId) return notify('Hãy chọn mã từ gợi ý'); const { error } = await supabase.rpc('record_portfolio_transaction', { p_portfolio_id: portfolio.data.id, p_symbol_id: symbolId, p_action: action, p_quantity: action === 'STOP_UPDATE' ? 0 : quantity, p_price: action === 'STOP_UPDATE' ? null : price || null, p_stop_price: stop || null, p_note: note || null }); if (error) return notify(`Không thể lưu giao dịch: ${error.message}`); client.invalidateQueries({ queryKey: ['portfolio'] }); client.invalidateQueries({ queryKey: ['journal'] }); setTradeOpen(false); notify(`${transactionLabels[action]} đã lưu; nhật ký được tạo tự động`) }
  return <section className="workspace-page"><div className="page-title-row"><div><h1>Danh mục</h1><p className="muted">Vị thế hiện tại, vốn và rủi ro. Giá: VND/cổ phiếu · Khối lượng: cổ phiếu.</p></div><div className="page-actions">{portfolio.data && <button className="secondary-button" onClick={openCapitalSetup}>Điều chỉnh vốn</button>}<button className="primary-button" onClick={() => portfolio.data ? openTrade() : openCapitalSetup()}><Plus size={16}/>{portfolio.data ? 'Giao dịch' : 'Khởi tạo danh mục'}</button></div></div>
    {!portfolio.isLoading && !portfolio.data && <article className="panel portfolio-empty"><h2>Khởi tạo vốn quản lý</h2><p>Nhập một lần để tính sức mua, phân bổ và rủi ro. Sau đó mọi Mua/Bán/Đóng vị thế đều đi qua một luồng giao dịch duy nhất.</p><button className="primary-button" onClick={openCapitalSetup}>Thiết lập vốn ban đầu</button></article>}
    <div className="metric-grid metric-grid-compact"><article className="metric-card"><span>Vốn quản lý</span><strong>{money(managed)}</strong></article><article className="metric-card"><span>Sức mua còn lại</span><strong>{money(Math.max(0, managed - deployed))}</strong></article></div>{concentration && <div className="risk-warning"><AlertTriangle size={18}/><span><strong>Cảnh báo tập trung:</strong> Ngành {concentration.label} chiếm {concentration.capitalPct.toFixed(0)}% tổng vốn — vượt ngưỡng 40%.</span></div>}
    <div className="analytics-grid"><article className="analytic-card"><h3>Phân bổ theo giá vốn</h3>{allocation.length ? <div className="donut-wrap"><div className="donut interactive-donut" style={{ background: donut }}><span>{positions.length}<small>vị thế</small></span></div><div className="legend">{allocation.map(item => <button type="button" className={hoveredSector === item.label ? 'active' : ''} onMouseEnter={() => setHoveredSector(item.label)} onFocus={() => setHoveredSector(item.label)} onMouseLeave={() => setHoveredSector(null)} onClick={() => setHoveredSector(value => value === item.label ? null : item.label)} key={item.label}><i style={{ background: item.color }}/>{item.label}<b>{item.pct.toFixed(0)}%</b></button>)}</div></div> : <p className="muted">Phân bổ sẽ xuất hiện khi có vị thế.</p>}{hovered && <div className="sector-donut-tooltip"><strong>{hovered.label}</strong><span>{hovered.pct.toFixed(1)}% vị thế · {hovered.capitalPct.toFixed(1)}% tổng vốn</span><small>{money(hovered.value)} giá vốn</small></div>}</article><article className="analytic-card"><h3>Kịch bản chạm dừng lỗ</h3><div className="risk-number"><strong>-{(managed ? totalRisk : 0).toFixed(1)}%</strong><span>tổng vốn</span></div><p className="muted">Mức sụt giảm tối đa nếu mọi vị thế đang mở chạm stop.</p><div className="risk-track danger"><i style={{ width: `${Math.min(totalRisk / 10 * 100, 100)}%` }}/></div></article><article className="analytic-card"><h3>Ngân sách rủi ro</h3><div className="budget-label"><span>Đã giải ngân</span><b>{money(deployed)} · {deployedPct.toFixed(1)}%</b></div><div className="risk-track"><i style={{ width: `${Math.min(deployedPct, 100)}%` }}/></div><div className="budget-label"><span>Rủi ro đã dùng / Giới hạn mỗi lệnh</span><b>{totalRisk.toFixed(1)}% / {portfolio.data?.max_risk_per_trade_pct ?? 0}%</b></div></article><article className="analytic-card"><h3>Gợi ý khối lượng mua</h3><div className="risk-number"><strong>{sizing ? sizing.toLocaleString('vi-VN') : '—'}</strong><span>cổ phiếu</span></div><p className="muted">Dựa trên vốn quản lý, stop và mức rủi ro mỗi lệnh.</p><div className="signal-preview"><WalletCards size={16}/> Giá và rủi ro đều tính bằng VND</div></article></div>
    <article className="panel"><div className="panel-title"><h3>Vị thế đang mở</h3><span>{positions.length} vị thế</span></div><div className="data-table"><div className="table-head"><span>Mã</span><span>Khối lượng</span><span>Giá vốn</span><span>Stop</span><span>Risk</span><span>Giao dịch</span></div>{positions.map(item => <div className="position-row" key={item.id}><strong>{item.symbols?.symbol}<small>{item.symbols?.sector}</small></strong><span>{Number(item.quantity).toLocaleString('vi-VN')} CP</span><span>{money(Number(item.average_cost))}</span><span>{item.stop_price ? money(Number(item.stop_price)) : '—'}</span><b>{managed ? (((Number(item.average_cost) - Number(item.stop_price)) * Number(item.quantity)) / managed * 100).toFixed(2) : '0.00'}%</b><div><button onClick={() => openTrade('BUY_ADD', item.symbols?.symbol)}>Mua thêm</button><button onClick={() => openTrade('SELL_REDUCE', item.symbols?.symbol)}>Bán</button><button onClick={() => openTrade('SELL_CLOSE', item.symbols?.symbol)}>Đóng</button></div></div>)}</div></article>
    {setupOpen && <div className="sheet-backdrop" onMouseDown={() => setSetupOpen(false)}><form className="bottom-sheet position-sheet rule-form" onSubmit={createPortfolio} onMouseDown={event => event.stopPropagation()}><div className="sheet-handle"/><div className="sheet-title"><h2>{portfolio.data ? 'Điều chỉnh vốn quản lý' : 'Khởi tạo danh mục'}</h2></div><CurrencyInput label="Vốn quản lý (VND)" value={initialCapital} onChange={setInitialCapital}/><label>Rủi ro tối đa mỗi lệnh (%)<input min="0.1" step="0.1" type="number" value={maxRisk} onChange={event => setMaxRisk(Number(event.target.value))}/></label><small className="muted">Vốn quản lý là mẫu số cho sức mua, phân bổ và rủi ro.</small><div className="form-sticky-actions"><button>{portfolio.data ? 'Lưu thay đổi' : 'Khởi tạo vốn'}</button></div></form></div>}
    {tradeOpen && <div className="sheet-backdrop" onMouseDown={() => setTradeOpen(false)}><form className="bottom-sheet position-sheet rule-form" onSubmit={submitTransaction} onMouseDown={event => event.stopPropagation()}><div className="sheet-handle"/><div className="sheet-title"><h2>Giao dịch danh mục</h2></div><SymbolAutocomplete symbols={symbols.data ?? []} value={symbol} onChange={setSymbol}/><label>Hành động<SoftSelect value={action} onChange={event => setAction(event.target.value as TransactionAction)}>{Object.entries(transactionLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</SoftSelect></label>{action !== 'STOP_UPDATE' && <><label>Khối lượng (cổ phiếu)<input min="1" step="1" type="number" value={quantity} onChange={event => setQuantity(Number(event.target.value))}/></label><CurrencyInput label="Giá giao dịch (VND/cổ phiếu)" value={price} onChange={setPrice}/></>}<CurrencyInput label={action === 'STOP_UPDATE' ? 'Stop mới (VND/cổ phiếu)' : 'Stop (VND/cổ phiếu, tuỳ chọn)'} value={stop} onChange={setStop}/><label>Lý do (tuỳ chọn)<textarea rows={3} value={note} onChange={event => setNote(event.target.value)} placeholder="Thêm lý do nếu cần"/></label><div className="form-sticky-actions"><button>{transactionLabels[action]}</button></div></form></div>}{toast && <div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</section>
}
