/** Reading guide shared by members and administrators. */
export function ScreenerGuide() {
  return <>
    <details className="guide-group" open><summary>Bộ lọc tín hiệu · bắt đầu từ đâu <small>EOD</small></summary><div className="guide-group-content">
      <p>Chọn Champion, Challenger hoặc Đối chiếu Song mã ở hàng trên cùng. Đọc ngày phiên trước khi xem mã: hệ thống chỉ dùng nến ngày, tuần, tháng đã đóng, không phải giá trực tiếp. Chọn mã để mở phân tích và xem vùng giá, lý do cùng mức vô hiệu.</p>
      <p><strong>Champion</strong> là tín hiệu tổng hợp đang công bố. <strong>Challenger</strong> là thí nghiệm song song; mọi đánh giá của nó chỉ nằm trong bảng nghiên cứu và không tạo giao dịch danh mục. <strong>Đối chiếu</strong> đặt hai kết quả của cùng mã, cùng phiên cạnh nhau.</p>
      <p>WATCH nghĩa là theo dõi hoặc bị một điều kiện chặn; PROBE_BUY là thăm dò, ADD là tăng vị thế, REDUCE và EXIT là giảm hoặc thoát. Một mẫu hình đẹp chưa tự động thành lệnh mua: còn phải qua thị trường, thanh khoản, stop và quy mô lệnh.</p>
    </div></details>
    <details className="guide-group"><summary>Bốn tab đọc tín hiệu <small>CHAMPION &amp; CHALLENGER</small></summary><div className="guide-group-content">
      <section><h3>1. Tín hiệu gốc</h3><p>Ở Champion, đây là tín hiệu tổng hợp đã công bố, có hành động, mức đồng thuận, bộ máy và lý do. Ở Challenger, card hiển thị quyết định tổng hợp cùng năm nhánh độc lập: Uptrend, Sideway, Phễu thích ứng, MACD đáy 2 và Spring phòng thủ. Các nhánh đều ghi WATCH khi chưa đủ điều kiện.</p></section>
      <section><h3>2. WATCH cơ hội</h3><p>Ở Champion, bảng gộp nhiều tín hiệu cùng mã, ưu tiên thay đổi mới, rủi ro của mã đang giữ, rồi cơ hội hình thành. Mở một mã để xem từng khung D/W/M và nút “Vì sao?”. Ở Challenger, tab hiện các đánh giá WATCH và lý do từng chiến lược chờ hoặc bị chặn; WATCH không phải khuyến nghị mua.</p></section>
      <section><h3>3. Phễu tháng → tuần → ngày</h3><p>Champion giữ phễu nghiên cứu với bối cảnh tháng UP. Challenger tính phễu riêng: tháng UP hoặc SIDEWAYS → setup tuần → trigger từ nến ngày đã đóng. Ở nhánh hồi hỗ trợ tuần, trigger ngày linh hoạt hơn breakout có volume lớn. Trạng thái tháng DOWN chưa mở nhánh này. H1 chưa có dữ liệu trong phạm vi EOD.</p></section>
      <section><h3>4. Phân kỳ Dương · đường MACD</h3><p>Champion hiển thị vùng phân kỳ và chờ xác nhận giá. Challenger tính tín hiệu riêng: đáy 1 đã xác nhận, đáy 2 tạm thời thấp hơn nhưng MACD cao hơn; nến xác nhận đóng mạnh khi MACD vừa cắt lên Signal có thể phát EARLY_PROBE. Tín hiệu phát sau đóng cửa và giả định mua sớm nhất Open phiên kế tiếp. Trong downtrend còn cần RSI dưới 25 hoặc chạm Bollinger dưới; Spring quá bán là nhánh riêng hiển thị cùng tab.</p></section>
    </div></details>
    <details className="guide-group"><summary>Đọc nhãn ở WATCH cơ hội <small>VÍ DỤ</small></summary><div className="guide-group-content">
      <section><h3>EXTENDED (+X%)</h3><p>Cảnh báo khi giá đóng cửa cao hơn mốc tham chiếu trên 7%. X = (giá đóng cửa / mốc tham chiếu − 1) × 100. Ví dụ 10.000 → 10.800 đồng là +8,0%. Mốc được lấy theo thứ tự giá nền, giá kích hoạt, rồi giá vô hiệu/stop nếu thiếu hai mốc đầu. Vì thế hãy mở bằng chứng để biết X đang đo từ mốc nào. Đây không phải lợi nhuận của vị thế hay mức lỗ đã xảy ra.</p></section>
      <section><h3>Ngành 65 · GTGD 12,3%</h3><p>65 là điểm sức khỏe ngành: tổng hợp tỷ lệ mã ở trên các đường trung bình và số mã tăng/giảm trong ngành. GTGD 12,3% nghĩa là ngành chiếm 12,3% giá trị giao dịch ước tính của các mã được quan sát trong universe ở phiên đó. Nó không đo tiền ròng chảy vào, mức tăng giá hay tỷ lệ tham gia lệnh cá nhân.</p></section>
      <section><h3>T0 · T1 · T2 · T_READY</h3><p>Tuổi lô hàng tính bằng phiên giao dịch: T0 là ngày mua, T1 còn chờ, T2 hàng về chiều và T_READY đã khả dụng hoàn toàn. Một mã có thể hiện nhiều thẻ nếu danh mục có nhiều lô mua khác ngày. Thẻ cho biết khả năng bán, không phải tín hiệu nên bán.</p></section>
    </div></details>
    <details className="guide-group"><summary>Chế độ thị trường Challenger và bảng đối chiếu <small>SHADOW</small></summary><div className="guide-group-content">
      <section><h3>UPTREND · SIDEWAYS · DOWNTREND</h3><p>Uptrend ưu tiên Breakout, VCP và Pullback. Sideway tìm Mean Reversion, Pocket Pivot hoặc Spring gần hỗ trợ và chặn breakout đỉnh 20 phiên; vùng chốt +7–10% chỉ là giả thuyết nghiên cứu. Downtrend mặc định đứng ngoài, khóa breakout; nhánh MACD đáy 2 hoặc Spring hoảng loạn mới được xét thăm dò. Spring hoảng loạn đòi hỏi quét thủng đáy với volume ít nhất 2× trung bình và nến kế tiếp lấy lại nền; đây là rule riêng, khác Spring volume thấp của Champion. Dữ liệu thị trường thiếu làm trạng thái UNKNOWN và không mở rủi ro mới.</p></section>
      <section><h3>MACD_EARLY_ZONE và quy mô</h3><p>EARLY_PROBE dùng 30% kích thước lệnh chuẩn và phải qua thanh khoản, tỷ lệ tham gia lệnh tối đa 5%, khoảng cách stop tối đa 8%. Trong downtrend, bảng ghi trần nghiên cứu 20% NAV cho tổng vị thế bắt đáy; ứng dụng chưa vận hành sổ lệnh Challenger nên không tự kiểm soát tổng vị thế thực tế. Hàng mua T chỉ bán được từ chiều T+2; mục tiêu MA20 hoặc +10–12% cũng là giả thuyết cần đo sau phí.</p></section>
      <section><h3>FTD và hồi phục</h3><p>Sau đáy, hệ thống theo dõi nỗ lực hồi phục và đánh dấu FTD từ ngày thứ tư trở đi khi VN-Index tăng ít nhất 1% với volume cao hơn phiên trước. Khi độ rộng phục hồi từ 40% trở lên, trạng thái RECOVERY_FTD có thể mở lại bộ lọc trung hạn với quy mô giảm. FTD có thể thất bại; đây là quy tắc nghiên cứu chứ không bảo đảm thị trường đã tạo đáy.</p></section>
      <section><h3>Đối chiếu Song mã</h3><p>ALIGNED là cùng hướng; EARLY_LEAD là Challenger thăm dò khi Champion chưa mua; CHASE_BLOCKED là chặn vì stop quá xa; SIDEWAY_REJECTED là từ chối breakout lúc thị trường đi ngang. Đọc lý do và bằng chứng trước khi diễn giải nhãn. Bảng điểm T+2 chỉ tính các tín hiệu đã đủ tuổi, sau phí mua/bán, thuế bán và trượt giá giả định; số mẫu ít hoặc dấu “—” không chứng minh bộ máy nào tốt hơn. Chỉ số ghép lượt tín hiệu không phải NAV danh mục.</p></section>
    </div></details>
  </>
}
