import { useEffect, useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowDownAZ, Download, Eye, Filter, LayoutGrid, List, Search, Star } from 'lucide-react'
import { supabase } from '../lib/supabase'

type SignalRow = { signal_id:string; symbol:string; sector:string|null; as_of_date:string; timeframe:string; action:string; score:number; reasons?:string[]; rule_name?:string }
type PricePoint = { symbol_id:string; trading_date:string; close:number; symbols?:{symbol:string}|null }

function Sparkline({ points }: { points:number[] }) { const values=points.slice(-20); if(values.length<2)return <span className="sparkline-empty">Chưa đủ 20 phiên</span>; const min=Math.min(...values),max=Math.max(...values),span=max-min||1; const polyline=values.map((value,index)=>`${index/(values.length-1)*100},${92-(value-min)/span*84}`).join(' '); const rising=values.at(-1)!>=values[0]; return <svg className={`sparkline ${rising?'up':'down'}`} viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Xu hướng giá 20 phiên"><polyline points={polyline}/></svg> }
const chipDefinitions=[['ALL','Tất cả'],['PROBE_BUY','🟢 Mua thăm dò'],['ADD','🔵 Mua gia tăng'],['EXIT','🔴 Cắt lỗ'],['SCORE80','Score ≥ 80'],['WATCHLIST','Watchlist ⭐']] as const

export function ScreenerPage({ authenticated }: { authenticated: boolean }) {
  const [query,setQuery]=useState(''); const [action,setAction]=useState('ALL'); const [minScore,setMinScore]=useState(0); const [descending,setDescending]=useState(true); const [view,setView]=useState<'table'|'cards'>(()=>localStorage.getItem('protstock-screener-view')==='cards'?'cards':'table'); const [favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('protstock-favorites')??'[]')}catch{return[]}})
  const signals=useQuery({queryKey:['signals'],enabled:authenticated&&Boolean(supabase),queryFn:async()=>{const{data,error}=await supabase!.from('effective_signals').select('signal_id,symbol,sector,as_of_date,timeframe,action,score,reasons,rule_name,pack_version,kind').order('as_of_date',{ascending:false}).order('score',{ascending:false}).limit(100);if(error)throw error;return data??[]}})
  const prices=useQuery({queryKey:['screener-sparklines'],enabled:authenticated&&Boolean(supabase),staleTime:300_000,queryFn:async()=>{const{data,error}=await supabase!.from('daily_prices').select('symbol_id,trading_date,close,symbols!inner(symbol)').order('trading_date',{ascending:false}).limit(5000);if(error)throw error;return data??[]}})
  useEffect(()=>{const sync=(event:Event)=>setFavorites((event as CustomEvent<string[]>).detail);addEventListener('protstock:favorites',sync);return()=>removeEventListener('protstock:favorites',sync)},[])
  const source=(signals.data??[]) as SignalRow[]
  const sparklineBySymbol=useMemo(()=>{const grouped:Record<string,PricePoint[]>={};((prices.data??[]) as unknown as PricePoint[]).forEach(point=>{const symbol=Array.isArray(point.symbols)?point.symbols[0]?.symbol:point.symbols?.symbol;if(symbol)(grouped[symbol]??=[]).push(point)});return Object.fromEntries(Object.entries(grouped).map(([symbol,items])=>[symbol,items.sort((a,b)=>a.trading_date.localeCompare(b.trading_date)).slice(-20).map(item=>Number(item.close))]))},[prices.data])
  const rows=useMemo(()=>source.filter(item=>(!query||item.symbol.toLowerCase().includes(query.toLowerCase()))&&(action==='ALL'||action==='SCORE80'&&item.score>=80||action==='WATCHLIST'&&favorites.includes(item.symbol)||item.action===action)&&item.score>=minScore).sort((a,b)=>(b.score-a.score)*(descending?1:-1)),[source,query,action,minScore,descending,favorites])
  function chooseChip(chip:string){setAction(chip);setMinScore(chip==='SCORE80'?80:0)}
  function setViewMode(next:'table'|'cards'){setView(next);localStorage.setItem('protstock-screener-view',next)}
  function toggleFavorite(symbol:string){const next=favorites.includes(symbol)?favorites.filter(item=>item!==symbol):[symbol,...favorites];setFavorites(next);localStorage.setItem('protstock-favorites',JSON.stringify(next));dispatchEvent(new CustomEvent('protstock:favorites',{detail:next}))}
  function openChart(symbol:string){localStorage.setItem('protstock-symbol',symbol);dispatchEvent(new CustomEvent('protstock:symbol',{detail:symbol}));location.hash='analysis'}
  function openJournal(symbol:string){localStorage.setItem('protstock-journal-symbol',symbol);location.hash='journal'}
  function exportCsv(){const csv=['Mã,Hành động,Khung,Điểm,Ngày,Rule',...rows.map(x=>[x.symbol,x.action,x.timeframe,x.score,x.as_of_date,x.rule_name].join(','))].join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='protstock-signals.csv';anchor.click();URL.revokeObjectURL(url)}
  const actions=(signal:SignalRow)=><div className="screener-actions"><button type="button" onClick={()=>openChart(signal.symbol)}><Eye size={13}/> Xem Chart</button><button type="button" className={favorites.includes(signal.symbol)?'active':''} onClick={()=>toggleFavorite(signal.symbol)}><Star size={13} fill={favorites.includes(signal.symbol)?'currentColor':'none'}/> Watchlist</button><button type="button" onClick={()=>openJournal(signal.symbol)}>📝 Ghi Journal</button></div>
  return <section className="workspace-page"><span className="eyebrow">SCREENER · EOD SIGNALS</span><div className="page-title-row"><div><h1>Bộ lọc tín hiệu</h1><p className="muted">Thu hẹp 202 mã thành danh sách hành động sau phiên.</p></div><button className="secondary-button export-button" onClick={exportCsv}><Download size={15}/> Xuất CSV</button></div>
    <div className="screener-controls"><div className="filter-pills" aria-label="Lọc nhanh">{chipDefinitions.map(([id,label])=><button type="button" className={action===id?'active':''} key={id} onClick={()=>chooseChip(id)}>{label}</button>)}</div><div className="view-switcher" aria-label="Chế độ xem"><button type="button" className={view==='table'?'active':''} onClick={()=>setViewMode('table')}><List size={15}/> Bảng gọn</button><button type="button" className={view==='cards'?'active':''} onClick={()=>setViewMode('cards')}><LayoutGrid size={15}/> Thẻ trực quan</button></div></div>
    <div className="filter-bar"><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm mã…"/></label><label><Filter size={15}/><select value={action} onChange={e=>chooseChip(e.target.value)}><option value="ALL">Mọi hành động</option>{['PROBE_BUY','ADD','WATCH','REDUCE','EXIT'].map(x=><option key={x}>{x}</option>)}</select></label><label>Điểm ≥ <input type="number" min="0" max="100" value={minScore} onChange={e=>{setMinScore(+e.target.value);setAction('ALL')}}/></label><button onClick={()=>setDescending(v=>!v)}><ArrowDownAZ size={15}/> Điểm {descending?'cao → thấp':'thấp → cao'}</button></div>
    <article className="panel"><div className="panel-title"><h3>Kết quả rule đang bật</h3><span>{rows.length} TÍN HIỆU</span></div>{view==='table'?<div className="data-table screener-table"><div className="table-head"><span>Mã</span><span>Hành động</span><span>Khung</span><span>Điểm</span><span>Lý do</span><span>Ngày</span></div>{rows.map(signal=><div className="position-row screener-row" key={signal.signal_id}><strong>{signal.symbol}<small>{signal.sector}</small></strong><span className="action-pill">{signal.action}</span><span>{signal.timeframe}</span><b>{signal.score}</b><span>{signal.reasons?.join(' · ')||signal.rule_name}</span><span>{signal.as_of_date}</span>{actions(signal)}</div>)}</div>:<div className="signal-visual-grid">{rows.map(signal=><article className="signal-visual-card" key={signal.signal_id}><div className="signal-visual-head"><span className="symbol-avatar">{signal.symbol.slice(0,2)}</span><div><strong>{signal.symbol}</strong><small>{signal.sector||'Chưa phân ngành'} · {signal.timeframe}</small></div><b>{signal.score}</b></div><span className="action-pill">{signal.action}</span><Sparkline points={sparklineBySymbol[signal.symbol]??[]}/><p>{signal.reasons?.join(' · ')||signal.rule_name||'Tín hiệu EOD'}</p><small>{signal.as_of_date} · xu hướng 20 phiên</small>{actions(signal)}</article>)}</div>}{!rows.length&&<p className="muted">Không có tín hiệu khớp bộ lọc hiện tại.</p>}</article>
  </section>
}
