/** Reading guide shared by members and administrators. */
export function ScreenerGuide() {
  return <>
    <details className="guide-group" open><summary>Bộ lọc tín hiệu · bắt đầu từ đâu <small>EOD</small></summary><div className="guide-group-content">
      <p>Chọn Champion, Challenger hoặc Đối chiếu Song mã ở hàng trên cùng. Đọc ngày phiên trước khi xem mã: hệ thống chỉ dùng nến ngày, tuần, tháng đã đóng, không phải giá trực tiếp. Chọn mã để mở phân tích và xem vùng giá, lý do cùng mức vô hiệu.</p>
      <p><strong>Champion</strong> là tín hiệu tổng hợp đang công bố. <strong>Challenger</strong> là thí nghiệm song song; mọi đánh giá của nó chỉ nằm trong bảng nghiên cứu và không tạo giao dịch danh mục. <strong>Đối chiếu</strong> đặt hai kết quả của cùng mã, cùng phiên cạnh nhau.</p>
      <p>WATCH nghĩa là theo dõi hoặc bị một điều kiện chặn; PROBE_BUY là thăm dò, ADD là tăng vị thế, REDUCE và EXIT là giảm hoặc thoát. Một mẫu hình đẹp chưa tự động thành lệnh mua: còn phải qua thị trường, thanh khoản, stop và quy mô lệnh.</p>
    </div></details>
    <details className="guide-group"><summary>Năm tab đọc tín hiệu <small>CHAMPION &amp; CHALLENGER</small></summary><div className="guide-group-content">
      <section><h3>1. Tín hiệu gốc</h3><p>Ở Champion, mỗi dòng là một tín hiệu tổng hợp đã công bố cho mã, khung D/W/M và phiên EOD: hành động, điểm đồng thuận 0–100, số bộ máy đồng thuận, mã lý do và phiên bản nguồn. Bộ lọc cơ bản chọn mã, hành động; bộ lọc nâng cao chọn khung, bộ máy, ngày; có bảng/thẻ và lịch sử. Điểm đồng thuận là mức hội tụ điều kiện, không phải xác suất thắng. Ở Challenger, một dòng là quyết định tổng hợp của cùng mã và phiên; năm nhánh độc lập gồm Uptrend, Sideway, Phễu thích ứng, MACD đáy 2 và Spring phòng thủ. Nhánh thiếu điều kiện ghi WATCH cùng lý do. Bảng điểm chiến lược chỉ tính mẫu đã đủ T+2.</p></section>
      <section><h3>2. WATCH cơ hội</h3><p>Ở Champion, bảng gộp nhiều tín hiệu cùng mã và ưu tiên thay đổi mới → rủi ro mã đang giữ → cơ hội hình thành. Lọc nhóm ưu tiên và vị thế; mở một mã để xem từng khung D/W/M, lý do và nút “Vì sao?”. Ở Challenger, chỉ các đánh giá tổng hợp WATCH được liệt kê. Lọc theo mã, hành động Champion, Delta Insight, chiến lược, ngành và khoảng cách nền để tìm nguyên nhân đang chờ hoặc bị chặn. WATCH không phải khuyến nghị mua.</p></section>
      <section><h3>3. Radar cơ hội</h3><p>Mỗi hàng tóm tắt diễn biến giá–khối lượng của một mã, tín hiệu Champion/WATCH, Phễu gốc, Phễu Challenger và phân kỳ MACD trong cùng phiên. Mở hàng để xem số liệu và liên kết đến đúng mã ở từng bảng. “Khoảng cách stop đạt sơ bộ” chỉ là kiểm tra rủi ro của Radar, không phải lệnh mua. Bộ lọc giai đoạn có thể tìm nhiều mốc trong cùng phiên, chẳng hạn vừa breakout ngày vừa xác nhận tuần.</p></section>
      <section><h3>4. Phễu tháng → tuần → ngày</h3><p>Cả hai tab phễu đều là bảng nghiên cứu: tab Champion dùng bộ phễu gốc, tab Challenger dùng phễu thích ứng. Phễu chỉ xét tuần và tháng đã đóng. Bộ gốc đi tiếp khi tháng UP; bộ thích ứng đi tiếp khi tháng UP hoặc SIDEWAYS. Trình tự là bối cảnh tháng → setup tuần còn hiệu lực → lần vượt ngưỡng mới trên nến ngày → cổng an toàn Challenger (nếu có) → hành động. Nhãn giai đoạn cho biết tiến độ, không phải lệnh mua. Bảng gốc hiển thị một hàng chính trên một dòng; mở Chi tiết để đọc mã điều kiện.</p></section>
      <section><h3>5. Phân kỳ Dương · đường MACD</h3><p>Champion ghép 2–4 vùng đáy giá với đáy đường MACD (ngày đáy có thể khác nhau), theo dõi chờ giá vượt ngưỡng và volume xác nhận; trạng thái có thể là chờ, xác nhận, vô hiệu hoặc hết hạn. Challenger có nhánh MACD_EARLY_ZONE riêng: đáy 1 đã xác nhận, đáy 2 tạm thời thấp hơn nhưng MACD cao hơn; nến đóng mạnh khi histogram vừa đổi sang dương có thể phát EARLY_PROBE. Đây là giao cắt MACD/Signal trong phiên, không phải quy tắc phân kỳ vùng của Champion. Nhánh DOWNTREND_SPRING tìm phiên quét đáy volume lớn rồi lấy lại hỗ trợ. Lọc mã, nhánh, hành động, regime, quá bán/Bollinger dưới, lý do và khoảng cách stop. Tín hiệu được tính sau đóng cửa; giá mua giả định sớm nhất là Open phiên kế tiếp.</p></section>
    </div></details>
    <details className="guide-group"><summary>Cấu trúc dữ liệu và cách đọc từng cột <small>TỪ ĐIỂN</small></summary><div className="guide-group-content">
      <section><h3>Đơn vị dữ liệu</h3><p>Mã là cổ phiếu trong universe; ngày là phiên EOD của assessment. D là nến ngày, W là tuần đã đóng, M là tháng đã đóng. Một mã có thể có nhiều tín hiệu Champion theo khung nhưng chỉ một đánh giá tổng hợp Challenger và một đánh giá cho mỗi nhánh trong cùng phiên. Dấu “—” nghĩa là chưa có hoặc chưa tính được dữ liệu, không phải giá trị 0.</p></section>
      <section><h3>Giá nền, stop và khoảng cách</h3><p>Giá nền là mốc setup/trigger tham chiếu; stop hay giá vô hiệu là mức làm hỏng giả thuyết. “Xa nền” = (giá đóng cửa / giá nền − 1) × 100%; “Xa stop” = (giá đóng cửa / stop − 1) × 100%. Hai khoảng cách có mốc khác nhau. Nếu thiếu mốc, cột để “—”. Challenger chặn điểm mua nghiên cứu khi xa stop trên 8% hoặc giá dưới stop.</p></section>
      <section><h3>Giai đoạn phễu và setup</h3>
        <p><strong>Bối cảnh tháng.</strong> Bộ gốc cần ít nhất 23 tháng đã đóng để xét EMA10, SMA20, xu hướng của hai đường và hai tháng đóng cửa gần nhất. Bộ thích ứng dùng cùng quy tắc khi đủ 23 tháng; với 6–22 tháng, dùng bối cảnh SMA6 rút gọn. Thiếu lịch sử thì tháng UNKNOWN. Bộ gốc chỉ đi tiếp khi UP; bộ thích ứng chấp nhận UP hoặc SIDEWAYS. Trạng thái tháng của cổ phiếu khác regime thị trường Challenger.</p>
        <p><strong>Setup tuần.</strong> Cần ít nhất 21 tuần đã đóng và volume bình quân 13 tuần trước lớn hơn 0.</p>
        <ul><li><strong>WEEKLY_BREAKOUT_13:</strong> tuần đóng trên đỉnh cao nhất 13 tuần trước, volume tuần ≥ 1,3× bình quân 13 tuần; ngưỡng ngày là đỉnh 13 tuần đó.</li><li><strong>WEEKLY_PULLBACK_EMA20:</strong> đáy tuần chạm hoặc dưới EMA20 tuần, đóng trên EMA20 và trên giá mở tuần; ngưỡng ngày là đỉnh tuần setup.</li><li><strong>WEEKLY_RANGE_SUPPORT (chỉ bộ thích ứng):</strong> đáy tuần đến gần đáy thấp nhất tám tuần trước (không quá 2% phía trên), tuần đóng trên hỗ trợ và trên giá mở; ngưỡng ngày là đỉnh phiên ngày trước.</li></ul>
        <p>Hai setup đầu vô hiệu khi một phiên sau setup đóng dưới đáy thấp nhất của tuần setup và ba tuần trước; hồi hỗ trợ vô hiệu khi đóng dưới đáy tuần setup.</p>
        <p><strong>Trigger ngày.</strong> Setup breakout đã xác nhận lúc đóng tuần có thể ghi nhận chính nến ngày cuối tuần nếu vượt ngưỡng. Pullback và hồi hỗ trợ xét từ phiên sau setup, tối đa 20 phiên giao dịch. Phải có đủ 20 phiên trước để tính volume bình quân; Close hôm trước ≤ ngưỡng và Close hôm nay &gt; ngưỡng. Breakout và pullback còn cần volume hôm nay ≥ 1,3× bình quân 20 phiên; hồi hỗ trợ tuần không cần mức 1,3× này. Nếu một phiên sau setup đóng dưới mức vô hiệu, setup bị loại. Phễu giữ trigger của setup gần nhất đã kích hoạt và còn hiệu lực khi có setup mới chưa kích hoạt.</p>
        <p><strong>Cách đọc giai đoạn.</strong> MONTHLY_CONTEXT: tháng chưa cho đi tiếp hoặc không có setup tuần hợp lệ; WEEKLY_READY: có setup nhưng chưa vượt ngưỡng; DAILY_TRIGGER: lần vượt ngưỡng đầu tiên ở phiên đang xem; TRIGGERED_EARLIER: lần vượt đã xảy ra trước đó trong setup này; DATA_QUARANTINED: chuỗi giá có đứt gãy lớn chưa xác minh. Ngày kích hoạt là ngày phát sinh lần vượt, không phải ngày mở vị thế.</p>
        <p>Ở nhánh ADAPTIVE_FUNNEL, chỉ DAILY_TRIGGER của phiên hiện tại mới tạo ứng viên PROBE_BUY; regime, xung đột với Champion, thanh khoản, tỷ lệ tham gia lệnh và khoảng cách stop vẫn có thể chuyển hành động thành WATCH. Lọc giai đoạn trước, rồi đọc setup, ngày kích hoạt, lý do và hành động; bộ đếm giai đoạn tính trên toàn tab, còn tổng kết quả tuân theo các bộ lọc hiện tại.</p>
      </section>
      <section><h3>Regime và nhánh Challenger</h3><p>UPTREND ưu tiên breakout/VCP/pullback; SIDEWAYS ưu tiên hồi về nền/Pocket Pivot và không mua breakout đỉnh 20 phiên; DOWNTREND phòng thủ, chỉ nghiên cứu MACD đáy 2 hoặc Spring khi có quá bán; RECOVERY_FTD là phục hồi được xác nhận theo quy tắc FTD với quy mô giảm; UNKNOWN là thiếu dữ liệu thị trường. Quy mô hiển thị là hệ số so với lệnh chuẩn, không phải phần trăm NAV đã mua. PROBE_BUY là thăm dò nghiên cứu; EARLY_PROBE là thăm dò sớm 30%; WATCH là chờ hoặc bị chặn.</p></section>
      <section><h3>Đối chiếu và hiệu quả T+2</h3><p>Champion là hành động đã công bố của cùng mã/cùng phiên; Challenger là quyết định shadow. Delta Insight phân loại sự khác biệt từ hành động và mã lý do. Bảng điểm dùng lợi suất ròng giả định tại T+2, drawdown trong thời gian khóa và profit factor = tổng lãi / tổng lỗ tuyệt đối. n là số lượt đủ tuổi; “—” là chưa có mẫu hoặc không tính được. “Chỉ số ghép lượt” nhân chuỗi lợi suất đơn vị, không phải NAV danh mục. Trạng thái T0/T1/T2/T_READY chỉ tuổi lô hàng đang giữ, không phải dự báo tín hiệu.</p></section>
    </div></details>
    <details className="guide-group"><summary>Đọc nhãn ở WATCH cơ hội <small>VÍ DỤ</small></summary><div className="guide-group-content">
      <section><h3>EXTENDED (+X%)</h3><p>Cảnh báo khi giá đóng cửa cao hơn mốc tham chiếu trên 7%. X = (giá đóng cửa / mốc tham chiếu − 1) × 100. Ví dụ 10.000 → 10.800 đồng là +8,0%. Mốc được lấy theo thứ tự giá nền, giá kích hoạt, rồi giá vô hiệu/stop nếu thiếu hai mốc đầu. Vì thế hãy mở bằng chứng để biết X đang đo từ mốc nào. Đây không phải lợi nhuận của vị thế hay mức lỗ đã xảy ra.</p></section>
      <section><h3>Ngành 65 · GTGD 12,3%</h3><p>65 là điểm sức khỏe ngành: tổng hợp tỷ lệ mã ở trên các đường trung bình và số mã tăng/giảm trong ngành. GTGD 12,3% nghĩa là ngành chiếm 12,3% giá trị giao dịch ước tính của các mã được quan sát trong universe ở phiên đó. Nó không đo tiền ròng chảy vào, mức tăng giá hay tỷ lệ tham gia lệnh cá nhân.</p></section>
      <section><h3>T0 · T1 · T2 · T_READY</h3><p>Tuổi lô hàng tính bằng phiên giao dịch: T0 là ngày mua, T1 còn chờ, T2 hàng về chiều và T_READY đã khả dụng hoàn toàn. Một mã có thể hiện nhiều thẻ nếu danh mục có nhiều lô mua khác ngày. Thẻ cho biết khả năng bán, không phải tín hiệu nên bán.</p></section>
    </div></details>
    <details className="guide-group"><summary>Chế độ thị trường Challenger và bảng đối chiếu <small>SHADOW</small></summary><div className="guide-group-content">
      <section><h3>UPTREND · SIDEWAYS · DOWNTREND</h3><p>Uptrend ưu tiên Breakout, VCP và Pullback. Sideway tìm Mean Reversion, Pocket Pivot hoặc Spring gần hỗ trợ và chặn breakout đỉnh 20 phiên; vùng chốt +7–10% chỉ là giả thuyết nghiên cứu. Downtrend mặc định đứng ngoài, khóa breakout; nhánh MACD đáy 2 hoặc Spring hoảng loạn mới được xét thăm dò. Spring hoảng loạn đòi hỏi quét thủng đáy với volume ít nhất 2× trung bình và nến kế tiếp lấy lại nền; đây là rule riêng, khác Spring volume thấp của Champion. Dữ liệu thị trường thiếu làm trạng thái UNKNOWN và không mở rủi ro mới.</p></section>
      <section><h3>MACD_EARLY_ZONE và quy mô</h3><p>EARLY_PROBE dùng 30% kích thước lệnh chuẩn và phải qua thanh khoản, tỷ lệ tham gia lệnh tối đa 5%, khoảng cách stop tối đa 8%. Trong downtrend, bảng ghi trần nghiên cứu 20% NAV cho tổng vị thế bắt đáy; ứng dụng chưa vận hành sổ lệnh Challenger nên không tự kiểm soát tổng vị thế thực tế. Hàng mua T chỉ bán được từ chiều T+2; mục tiêu MA20 hoặc +10–12% cũng là giả thuyết cần đo sau phí.</p></section>
      <section><h3>FTD và hồi phục</h3><p>Sau đáy, hệ thống theo dõi nỗ lực hồi phục và đánh dấu FTD từ ngày thứ tư trở đi khi VN-Index tăng ít nhất 1% với volume cao hơn phiên trước. Khi độ rộng phục hồi từ 40% trở lên, trạng thái RECOVERY_FTD có thể mở lại bộ lọc trung hạn với quy mô giảm. FTD có thể thất bại; đây là quy tắc nghiên cứu chứ không bảo đảm thị trường đã tạo đáy.</p></section>
      <section><h3>Đối chiếu Song mã</h3><p>ALIGNED là cùng hành động hoặc Challenger thăm dò sớm khi Champion cũng có nhãn mua; nhãn này có thể gồm cả hai bên WATCH. EARLY_LEAD là Challenger thăm dò khi Champion chưa mua, chưa đo số phiên dẫn trước. CHASE_BLOCKED là chặn vì stop quá xa hoặc giá dưới stop; SIDEWAY_REJECTED là từ chối breakout lúc thị trường đi ngang; DIFFERENT là các trường hợp còn lại. Lọc theo hành động hai bên, nhãn, nhánh chiến lược, ngành, xa nền, điểm ngành, T+ hoặc mã lý do. Bảng điểm T+2 chỉ tính các tín hiệu đã đủ tuổi, sau phí mua/bán, thuế bán và trượt giá giả định; số mẫu ít hoặc dấu “—” không chứng minh bộ máy nào tốt hơn. Chỉ số ghép lượt tín hiệu không phải NAV danh mục.</p></section>
    </div></details>
  </>
}
