import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import type { UserProfile } from '../AuthGate'
import { supabase } from '../lib/supabase'
import { version } from '../../package.json'
import { TodayHealth } from './TodayHealth'
import { ReplayPanel } from './ReplayPanel'
import { EngineGuide } from './EngineGuide'
import { ScreenerGuide } from './ScreenerGuide'
import { VersionHistory } from './VersionHistory'
export function SettingsPage({ authenticated, isAdmin = true, profile }: { authenticated: boolean; isAdmin?: boolean; profile?: UserProfile | null }) {
  const [tab, setTab] = useState<'guide' | 'data' | 'account' | 'version'>('guide')
  const rules = useQuery({ queryKey: ['guide-rules'], enabled: authenticated && Boolean(supabase) && isAdmin, queryFn: async () => { const { data, error } = await supabase!.from('rules').select('id,name,status,rule_versions(version)').order('name'); if (error) throw error; return data ?? [] } })
  return <section className="workspace-page settings-page">
    <div className="page-title-row"><div><h1>Cài đặt</h1><p className="muted">Dữ liệu, hướng dẫn, phiên bản và tài khoản.</p></div></div>
    <div className="timeframe-tabs" role="tablist" aria-label="Cài đặt">{([['guide','Hướng dẫn'],['data','Dữ liệu'],['version','Phiên bản'],['account','Tài khoản']] as const).map(([id,label])=><button key={id} id={`settings-tab-${id}`} role="tab" aria-selected={tab===id} aria-controls="settings-panel" className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    <div id="settings-panel" role="tabpanel" aria-labelledby={`settings-tab-${tab}`}>
    {tab==='version'?<VersionHistory currentVersion={version}/>
    :tab==='data'?<><TodayHealth/><article className="panel"><h2>Cách đọc dữ liệu</h2><p>Giá hiển thị bằng VND/cổ phiếu; vốn và báo cáo bằng VND. Tín hiệu sử dụng ngày công bố và phiên bản thuật toán cụ thể. D/W/M chỉ tạo quyết định từ nến đã đóng.</p><p>Prot Flow là áp lực giá–khối lượng, điểm mẫu hình là thước đo cấu trúc. Phân ngành lịch sử hiện dùng phân loại ngành đang lưu. Dữ liệu sự kiện doanh nghiệp chưa được thu thập đầy đủ; kiểm thử có thể bị ảnh hưởng bởi chia tách hoặc cổ tức.</p><p>Nguồn hiện tại: KBS. Tốc độ cập nhật phụ thuộc giới hạn nguồn dữ liệu và hàng đợi GitHub Actions.</p></article></>
    :tab==='account'?<article className="panel account-panel"><h2>Tài khoản</h2><div className="rule-row"><strong>{profile?.full_name || profile?.username || 'Chưa kết nối'}</strong><span>{profile?.role==='ADMIN'?'Quản trị':'Thành viên'}</span></div><p>Phiên bản v{version}. Luận điểm và bản nháp cá nhân được gắn với tài khoản; lịch sử phiên bản được giữ khi cập nhật.</p><button className="secondary-button" disabled={!authenticated} onClick={()=>void supabase?.auth.signOut()}>Đăng xuất</button>{isAdmin&&<ReplayPanel/>}</article>
    :isAdmin?<>{rules.isError&&<p role="alert">Chưa tải được quy tắc. <button className="text-button" onClick={()=>void rules.refetch()}>Thử lại</button></p>}<Guide authenticated={authenticated} rules={rules.data??[]} loading={rules.isLoading} includeIntro/></>:<div className="guide-list"><Intro/><ScreenerGuide/></div>}
    </div>
  </section>
}
function Intro(){return <article className="panel app-intro-card"><h2>Prot Stock v{version}</h2><p>Công cụ cá nhân để theo dõi thị trường, phân tích đa khung, quản lý luận điểm và xem lại quyết định đầu tư.</p><p>Đi từ Tổng quan → Watchlist → Phân tích mã. Ghi lý do đầu tư, điều kiện vô hiệu và nhật ký tại thời điểm quyết định.</p><p>Dữ liệu cập nhật sau phiên giao dịch; xem ngày công bố và độ phủ trong mục Dữ liệu trước khi sử dụng.</p></article>}
function Guide({ authenticated, rules, loading, includeIntro }: { authenticated: boolean; rules: any[]; loading: boolean; includeIntro: boolean }) {
  const active = rules.filter(rule => rule.status === 'ACTIVE'); const core = active.filter(rule => String(rule.name).startsWith('Prot Core')); const latestVersion = Math.max(0, ...core.flatMap(rule => rule.rule_versions ?? []).map((version: any) => Number(version.version)))
  return <div className="guide-list">{includeIntro&&<Intro/>}<a className="guide-universe-card" href="#universe"><span>Danh mục</span><strong>Danh sách cổ phiếu</strong><small>Xem đầy đủ mã đang hoạt động và tải danh sách.</small></a><ScreenerGuide/><EngineGuide/>
    <details className="guide-group"><summary>Phễu nghiên cứu đa khung <small>MULTI-TIMEFRAME</small></summary><div className="guide-group-content"><h2>Tháng → setup tuần → trigger ngày</h2><p>Bộ phễu gốc và phễu Challenger thích ứng chỉ dùng tháng, tuần đã đóng; quy tắc đầy đủ cho từng setup và ngưỡng ngày nằm ở mục “Cấu trúc dữ liệu và cách đọc từng cột” phía trên. Đây là đánh giá nghiên cứu, không tự tạo giao dịch.</p><section><h3>1. Bối cảnh tháng</h3><p>Bộ gốc chỉ đi tiếp khi trạng thái tháng UP. Bộ thích ứng đi tiếp khi UP hoặc SIDEWAYS; thiếu lịch sử là UNKNOWN. Trạng thái này khác regime thị trường Challenger.</p></section><section><h3>2. Setup tuần</h3><p>Setup breakout 13 tuần, pullback EMA20 hoặc hồi hỗ trợ tám tuần chỉ được xét trong tối đa 20 phiên sau tuần setup và bị loại khi có phiên đóng dưới mức vô hiệu.</p></section><section><h3>3. Trigger ngày</h3><p>Close phiên trước không vượt ngưỡng, Close phiên xét vượt ngưỡng. Riêng setup breakout được xác nhận lúc đóng tuần có thể ghi nhận chính nến ngày cuối tuần nếu nến đó vượt ngưỡng; không đợi cổ phiếu quay xuống rồi vượt lại. Cần 20 phiên trước để tính volume bình quân; breakout và pullback còn cần volume phiên xét đạt ít nhất 1,3× bình quân này. Hồi hỗ trợ tuần dùng đỉnh phiên trước làm ngưỡng, không bắt buộc volume 1,3×. Không dùng RSI/MACD làm điều kiện trigger của phễu. Ở Challenger, trigger còn phải qua các cổng an toàn mới có thể thành PROBE_BUY.</p></section></div></details>
    <details className="guide-group"><summary>Radar đà tăng <small>NGHIÊN CỨU EOD</small></summary><div className="guide-group-content"><p>Radar ghi nhận sớm phiên tăng giá và khối lượng nổi bật, breakout ngày, xác nhận tuần, đà tiếp diễn, tăng tốc lại và mất hiệu lực. Các mốc của cùng đợt tăng dùng chung mã sự kiện; setup tuần mới không xóa diễn biến trước.</p><p>Cột điểm vào tách riêng khỏi phát hiện. Nếu giá cách stop cấu trúc quá 8%, Radar gắn “quá xa stop”; không xem đó là điểm mua. Khối lượng giao dịch không đồng nghĩa dòng tiền mua ròng. Radar không phát lệnh Champion.</p></div></details>
    <details className="guide-group"><summary>Thiết lập quy tắc <small>{loading ? 'ĐANG TẢI' : `${active.length} ACTIVE`}</small></summary><div className="guide-group-content"><h2>Quy tắc là điều kiện, không phải lời khuyên</h2><p>Prot mô tả bằng tiếng Việt; app biên dịch thành DSL được kiểm tra và lưu version.</p><section><h3>Quy tắc nền tảng hiện tại</h3><p><strong>{latestVersion ? `Danh mục engine · phiên bản cấu hình ${latestVersion}` : 'Chưa có Core Rules'}</strong> · {core.length} quy tắc nền tảng đang bật · tổng {active.length} quy tắc đang bật.</p><ul>{core.map(rule => <li key={rule.id}>{rule.name}</li>)}{!core.length && <li>Chưa đọc được quy tắc từ Supabase.</li>}</ul></section><section><h3>Các điều kiện hỗ trợ</h3><p>Breakout, volume, MA stack, RSI, thanh khoản, sức mạnh tương đối, trạng thái VN-Index/ngành, stop-loss, trailing stop và time-stop.</p></section></div></details>
    <details className="guide-group"><summary>Đọc tín hiệu đúng cách <small>KỶ LUẬT</small></summary><div className="guide-group-content"><p>Tín hiệu là giả thuyết có điều kiện. Luôn kiểm tra mẫu hình, vùng vô hiệu, thanh khoản, trạng thái thị trường và rủi ro vị thế trước khi quyết định.</p></div></details>
    <details className="guide-group"><summary>Lịch vận hành EOD <small>GIỜ VIỆT NAM</small></summary><div className="guide-group-content"><div className="eod-stepper"><section><i>1</i><div><h3>GitHub Fast Lane · 15:30</h3><p>Thứ Hai–Thứ Sáu, Fast Lane tải giá, tính D/W/M, mẫu hình, vùng giá và các Core Engine. Hệ thống công bố phiên hoàn chỉnh khi đạt kiểm tra độ phủ. Dữ liệu thiếu được ghi rõ, không đánh dấu hoàn tất giả.</p></div></section><section><i>2</i><div><h3>Watchdog · 15:35 / 16:15</h3><p>Watchdog kiểm tra EOD hôm nay. Nếu chưa có hoặc lỗi, nó tự dispatch Fast Lane; nếu đã đủ thì không chạy trùng.</p></div></section><section><i>3</i><div><h3>Watchdog · 16:45</h3><p>Kiểm tra lần cuối. Chỉ thử lại mã còn thiếu, giới hạn số lần chạy và kiểm tra heartbeat để tránh treo hoặc chạy trùng. Lịch GitHub có thể chậm theo hàng đợi dịch vụ.</p></div></section><section><i>4</i><div><h3>Tín hiệu &amp; lịch sử</h3><p>PROBE_BUY/ADD/REDUCE/EXIT được tách với WATCH. Nạp lịch sử chạy theo lô; kiểm thử dùng vốn VND, khớp giá mở cửa phiên kế tiếp và giữ dữ liệu khởi động chỉ báo.</p></div></section></div></div></details>
  </div>
}
