import { useMemo, useState } from 'react'
import { Download, Search } from 'lucide-react'
import { useSymbols } from '../hooks/useStockAnalysis'
import { downloadUniverseExcel, type StockUniverseExportRow } from '../lib/stock-universe-export'

export function UniversePage({ authenticated }: { authenticated: boolean }) {
  const symbols = useSymbols(authenticated)
  const initial = new URLSearchParams(location.hash.split('?')[1] ?? '')
  const [query, setQuery] = useState('')
  const [sector, setSector] = useState(initial.get('sector') ?? '')
  const [exchange, setExchange] = useState(initial.get('exchange') ?? '')
  const universe = useMemo<StockUniverseExportRow[]>(() => (symbols.data ?? []).map((item: any) => ({ index: 0, symbol: String(item.symbol ?? ''), companyName: item.company_name || 'Chưa cập nhật', sector: item.sector || 'Chưa phân ngành', exchange: item.exchange === 'HOSE' ? 'HSX' : item.exchange || 'Chưa cập nhật' })).sort((a, b) => a.symbol.localeCompare(b.symbol, 'en')).map((item, index) => ({ ...item, index: index + 1 })), [symbols.data])
  const sectors = [...new Set(universe.map(item => item.sector))].sort((a,b) => a.localeCompare(b, 'vi'))
  const exchanges = [...new Set(universe.map(item => item.exchange))].sort((a,b) => a.localeCompare(b, 'vi'))
  const filtered = universe.filter(item => (!sector || item.sector === sector) && (!exchange || item.exchange === (exchange === 'HOSE' ? 'HSX' : exchange)) && (!query.trim() || `${item.symbol} ${item.companyName} ${item.sector}`.toLocaleLowerCase('vi').includes(query.trim().toLocaleLowerCase('vi'))))
  return <section className="workspace-page universe-page"><header className="universe-page-heading"><div><a href="#market">← Thị trường</a><h1>Danh sách cổ phiếu</h1><p>Danh sách mã đang hoạt động trong Prot Trading Universe, sắp xếp từ A đến Z.</p></div><button type="button" className="primary-button universe-download-button" onClick={() => downloadUniverseExcel(filtered)} disabled={!filtered.length}><Download size={16}/> Tải danh sách</button></header><article className="panel universe-list-panel"><div className="panel-title"><h3>{symbols.isLoading ? 'Đang tải danh sách…' : `${filtered.length}/${universe.length} mã cổ phiếu`}</h3><span>DANH SÁCH</span></div><div className="universe-filters"><label><Search size={15}/><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Tìm mã hoặc tên công ty" aria-label="Tìm cổ phiếu"/></label><select aria-label="Lọc theo nhóm ngành" value={sector} onChange={event => setSector(event.target.value)}><option value="">Tất cả nhóm ngành</option>{sectors.map(item => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Lọc theo sàn" value={exchange === 'HOSE' ? 'HSX' : exchange} onChange={event => setExchange(event.target.value)}><option value="">Tất cả sàn</option>{exchanges.map(item => <option key={item} value={item}>{item}</option>)}</select></div>{symbols.isError ? <p className="form-error">Không thể tải danh sách cổ phiếu. Thử lại sau.</p> : <div className="data-table universe-table"><div className="table-head"><span>STT</span><span>Mã</span><span>Tên công ty</span><span>Nhóm ngành</span><span>Sàn</span></div>{filtered.map((stock,index) => <div className="position-row" key={stock.symbol}><span>{index + 1}</span><strong>{stock.symbol}</strong><span>{stock.companyName}</span><span>{stock.sector}</span><span>{stock.exchange}</span></div>)}{!symbols.isLoading && !filtered.length && <p className="muted">Không có mã phù hợp bộ lọc.</p>}</div>}</article></section>
}
